### ISSUE TITLE
Incompatibility Issue - "WTF's Expedition: CaveBiomes, Ores, Trees, and Tweaks"

### ISSUE THREAD

**Issue by XvSkItZvX** [CreativeMD/EnhancedVisuals#10]
As I am unsure of the actual cause of the crash this issue will be duplicated on both Mod pages.

[Latest Error Report](http://pastebin.com/5L13i4RK ) - Can supply 4 others if needed.
Current [List of Mods](http://www.modlister.com/user/XvSkItZvX/%20Trouble%20Shooting%20Snapshot%20One)) in this package.
Enhanced Visuals Release: EnhancedVisuals v1.0.9 mc1.9-1.10.jar
"WTF's Expedition: CaveBiomes, Ores, Trees, and Tweaks Release: WTF-Expedition_1.10.2_v1.3.6.jar

This issue causes a game crash. Which was discovered when testing the features for the latest release of "Enhanced Visuals". Basically I was blowing myself up to see how it responded.

It wasn't a consistent issue, presenting about 3 out of 10 times. However being in close proximity(2-3 blocks) to an explosion, both Creeper and TNT, would result in "Internal Server Shutting Down" and the client closing.

I created a clean instance to test further and the issue didn't persist. I went back into my initial package and disabled the explosion tweaks in WTF and the problem went away in the pack as well.

Additionally, interaction between the two mods makes Enhanced Visuals explosion effects extreme. Bleaching out the screen entirely, that doesn't seem to go away until dunking it water, and incredibly loud 'beep'. 

I'm going to assume that because both mods seem to use a formula, this some how causes explosions to behave oddly. 

A work around to let your users know about is to disable the explosion tweak in the WTF mod.

As an aside which really was only inconvenient while the screen was completely whited out due to the above interactions. The dust effects from Enhanced Visuals obstruct the menu screen and the after death dialog for the client until the user manages to click respawn or enter a body of water. It may be useful to clear dust if the menu is opened or upon death, at least temporarily....

**Comment by XvSkItZvX** [comment]
Whisky responded, suggested I link here.. https://github.com/WhiskyTangoFawks/Expedition/issues/98#issuecomment-278867236

**Comment by XvSkItZvX** [comment]
Enhanced Visuals Version: EnhancedVisuals v1.0.10 mc1.9-1.10.jar
[Crash Report](http://pastebin.com/L16dNWiL)

I grabbed that download from the WTF thread and went to put it back through the same testing I did yesterday. Unfortunately I was able to recreate the problem on the first test.

This is all using default settings for the explosion tweaks in the WTF and EV mods. 

I'm standing 2 blocks away from the a block of TNT and using a lever to detonate and letting it blow my character up. At the moment of explosion the internal server shuts down and takes the client with it.

**Comment by CreativeMD** [comment]
Could try it out as well, just redownload it. I tested it myself multiple times with any crash, but yes together with WTF Expeditions you need to tweak the explosions a bit.
https://www.dropbox.com/s/ehz39pkvrfwsucy/EnhancedVisuals%20v1.0.10%20mc1.9-1.10.jar?dl=1

**Comment by XvSkItZvX** [comment]
Yeah I already have the 1.0.10 version you posted on drop box. That's what I was testing in the above post and it still crashed. I know that disabling the WTF Expeditions keeps it from crashing which is what I have been doing. Did you have tweaks to their settings that prevented the crash without disabling it completely?

**Comment by CreativeMD** [comment]
It's not the same file, just redownload it and test it again. I used the default configuration.

**Comment by XvSkItZvX** [comment]
It'll be later this evening but I'll get to it...thanks..

**Comment by XvSkItZvX** [comment]
The project I was planning on working on fell through so I managed to work out testing on it sooner than expected. 

Good news and bad news. 

After blowing myself up around 5 times no crash....awesome...

However, I'm afraid I don't understand the config settings enough to change the amount of time, or how much, of the dust effect covers the screen. This leaves the user blinded by a stark white screen for upwards of 5 minutes or more. Unfortunately during this time the player will be unable to view inventory, or menu screen either.

During one test I did not wear armor or eat an enchanted golden apple, which is how I've been surviving the tests, and subsequently died performing the test. I was thrilled to see that the white screen disappeared and I was able choose to respawn. 

Upon respawning though the screen was completely white again and I was unable to see even the inventory or menu. I do however know that the menu was able to be opened because I managed to exit the game with a bit of guess work. Upon returning to the game everything was back to normal.

I also managed to note by observing the, Waila element that I appeared to be experiencing substantial frame rate drops, which I was able to confirm as the smoke cleared I had dropped down to 5-6 FPS until I managed to find water...

When I jump into water I experience one last huge frame drop then once the screen clears I jump back up to where it normally rides, which is 110-120 fps normally.

I have no Error Report to link to because there was no crash. I do use optifine but I do not have fast render enabled. Additionally for frame rate losses I'm actually running a fairly beefy system so I wouldn't expect it to be an over taxing of the PC.

If there is anything else I can do to help test this feel free to let me know.

**Comment by CreativeMD** [comment]
Yeah, had the same issue during testing, that's why i said it needs some configuration.

There are multiple things you can configure

One thing is to decrease the dust multiplier. You can find that option inside the "dust" category:
> S:multiplier=10.0

maybe change it to one or even lower.

You can also take a look inside the "explosion" category:

> explosion {
>     # time of blur = time of muted sounds / blurTimeFactor [range: 0.0 ~ 100000.0, default: 2.5]
>     S:blurTimeFactor=2.5
> 
>     # time = Math.max(maxExplosionTime, damage*explosionTimeModifier) [range: 0.0 ~ 100000.0, default: 20.0]
>     S:explosionTimeModifier=20.0
> 
>     # volume of beep = damage/ConfigCore.explosionVolumeModifier [range: 0.0 ~ 100000.0, default: 10.0]
>     S:explosionVolumeModifier=10.0
> 
>     # max volume of a beep [range: 0.0 ~ 100000.0, default: 0.5]
>     S:maxBeepVolume=0.8
> 
>     # max blur effect [range: 0.0 ~ 100000.0, default: 100.0]
>     S:maxBlur=100.0
> 
>     # maximum explosion duration [range: 0 ~ 100000, default: 1000]
>     I:maxExplosionTime=1000
> 
>     # factor of all other sounsd (muting effect) [range: 0.0 ~ 100000.0, default: 0.0]
>     S:minExplosionVolume=0.0
> }

should be self explaining if not feel free to ask, but for now i call this issue fixed.
