### ISSUE TITLE
Color slowly desaturates to black and white?

### ISSUE THREAD

**Issue by DarklightDreamer** [CreativeMD/EnhancedVisuals#100]
For some reason, this mod is causing the color of my game to slowly desaturate from full color to completely black and white over the course of about 2 minutes after starting the game. Might be an Optifine or Mod compatibility issue, but Fast Render, Anisotropic Filtering and Antialiasing are all turned off.

Weirdly, it worked perfectly fine before, but this issue started seemingly randomly, and doesn't happen if I start a new world, so I'm not sure what I did to trigger it.

I'm on Windows 10, Forge 1.19.2, and a lot of mods installed currently.

**Comment by CreativeMD** [comment]
It's a feature, if you are low on hunger. If you are in creative mode it might not make sense. In theory all effects are disabled when you are in creative. You can either change the configuration so effects only work in survival using the command /cmdclientconfig or you can go to survival eat something and go back to creative mode.
