### ISSUE TITLE
Blood is white

### ISSUE THREAD

**Issue by JupiterboyLuffy** [CreativeMD/EnhancedVisuals#101]
For some reason, the blood when I get damaged is white in 1.19.

**Comment by CreativeMD** [comment]
Fabric or Forge? What version of the mod are you using? Any other mods installed?

Sorry for responding late.

**Comment by JupiterboyLuffy** [comment]
Forge. I have camera overhaul, and first person model installed.

**Comment by CreativeMD** [comment]
Can you try it without First person model installed and see if the issue is still there?

**Comment by JupiterboyLuffy** [comment]
ok

**Comment by JupiterboyLuffy** [comment]
the blood is still white

**Comment by CreativeMD** [comment]
So you only have Camera Overhaul and EnhancedVisuals installed? Does it still not work if you only install EnhancedVisuals (remove Camera Overhaul as well)?

**Comment by JupiterboyLuffy** [comment]
Let me try that

**Comment by CreativeMD** [comment]
The newest version should hopefully fix your issue! If not just reply here and I will reopen the issue again.
