### ISSUE TITLE
FancyMenu Incompatibility

### ISSUE THREAD

**Issue by thrasos-dev** [CreativeMD/EnhancedVisuals#103]
Fancy Menu Version: fancymenu_fabric_2.13.0_MC_1.19-1.19.2
Enhanced Visuals Version: EnhancedVisuals_FABRIC_v1.5.9_mc1.19.2

Intro animation & the background slideshows seem broken. The animation now has too much exposure and the slideshows' frame-rate and opacity have been reduced. The issue seems to be resolved when rolling back to version "EnhancedVisuals_FABRIC_v1.5.8_mc1.19.1".

Visual aid: https://imgur.com/a/Sz2EpUH

**Comment by CreativeMD** [comment]
Could you try out the newest version of EnhancedVisuals and see if it is fixed?

**Comment by thrasos-dev** [comment]
Hello, I have tried out the new version, namely [EnhancedVisuals_FABRIC_v1.5.10_mc1.19.3.jar](https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals/files/4174445), but the game is crashing. I am guessing it is not compatible with 1.19.2?

**Comment by CreativeMD** [comment]
Hey, yeah sorry. I have dropped support for 1.19.2. It just doesn't make sense. Can you update to 1.19.3?

**Comment by thrasos-dev** [comment]
Understandably... I will eventually update the modpack to 1.19.3, once all the mods have updated to this version as well (which might take a bit of time). For now I will be closing this issue, and if I have problems with the 1.19.3 version, I will re-open it. Thank you very much for your assistance.

**Comment by kasperbjerby** [comment]
Made a port to 1.19.2 of the newest verion with FanyMenu fixed

https://mega.nz/file/ULwl3LrL#x291CuGBnrm19MkC9zB7hsCbUzuPTNdiXN3lgpJquro

Edit: Ohh sorry, just saw you are using fabric, this one is forge 😅
