### ISSUE TITLE
When entering water or getting to low hearts this weird "symbol" appears.

### ISSUE THREAD

**Issue by Aerhtjiz** [CreativeMD/EnhancedVisuals#104]
Whenever I enter water or when the heartbeat starts on low hearts a weird "symbol" I dont know what it is appears below the crosshair.
Here is a video for it sorry there isn't sound havent figured out obs yet :)

https://www.dropbox.com/s/bssx999qypl6odq/2022-12-22%2013-26-56.mkv?dl=0

**Comment by CreativeMD** [comment]
What version are you using?

**Comment by Aerhtjiz** [comment]
1.18.2, forge 40.1.87, mod version 1.5.10

**Comment by Aerhtjiz** [comment]
> What version are you using?

1.18.2, forge 40.1.87, mod version 1.5.10

**Comment by CreativeMD** [comment]
I have released a new version for 1.18.2 which should fix this issue.
