### ISSUE TITLE
Low HP effects will still play even if max health is reduced.

### ISSUE THREAD

**Issue by Kokonico** [CreativeMD/EnhancedVisuals#105]
I am making a game in Diamondfire and when I reduce the players max hp attribute to 4, the low hp effect will play. (despite me being at "full " hp)

https://user-images.githubusercontent.com/96935064/209585386-fd84c462-0600-407d-9453-2ef54670b39d.mp4

**Comment by CreativeMD** [comment]
You can configure it using /cmdclientconfig. Normally it uses the `maxHealth` option, which is configued to 6 (which is 3 hearts). There is another option called `useHealthPercentage`, if you set it to true it will use the `maxHealthPercentage` (in this case the heartbeat effect will appear once you have 30% or less health. You can configure the values as you want to.
Hope that solves your issue.
