### ISSUE TITLE
effects stuck on upper-left corner

### ISSUE THREAD

**Issue by k0nstruct** [CreativeMD/EnhancedVisuals#106]
When using Quilt on MultiMC, the effects are stuck on a smaller screen on the upper left corner. 
To replicate: 
-Install creativecore + enhancedvisuals
-Launch Quilt on MultiMC
-Walk on sand or use any effect
![image](https://user-images.githubusercontent.com/95828007/210219563-fe0c2eae-85ac-4087-a5ca-8003989a1db0.png)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 248906616 bytes (237 MiB) / 1245708288 bytes (1188 MiB) up to 8455716864 bytes (8064 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2756
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22736.67
	Virtual memory used (MB): 17830.86
	Swap memory total (MB): 6417.13
	Swap memory used (MB): 164.27
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms768m -Xmx8064m
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		| Index | Mod                                                                   | ID                                                    | Version                      |
		|------:|-----------------------------------------------------------------------|-------------------------------------------------------|------------------------------|
		|    86 | Amecs API                                                             | amecsapi                                              | 1.3.6+mc1.19.3               |
		|    18 | AntiGhost                                                             | antighost                                             | 1.19.3-fabric0.68.1-1.1.5    |
		|   140 | AppleSkin                                                             | appleskin                                             | 2.4.2+mc1.19.3               |
		|   171 | Architectury                                                          | architectury                                          | 7.0.66                       |
		|    12 | Blur (Fabric)                                                         | blur                                                  | 2.6.1                        |
		|   165 | Bobby                                                                 | bobby                                                 | 4.0.3                        |
		|   186 | Capes                                                                 | capes                                                 | 1.5.1+1.19.3                 |
		|   119 | Cloth Config v9                                                       | cloth-config                                          | 9.0.94                       |
		|    82 | Coat                                                                  | coat                                                  | 1.0.0-beta.19+mc1.19.3       |
		|   105 | Concurrent Chunk Management Engine                                    | c2me                                                  | 0.2.0+alpha.9.12             |
		|    80 | Concurrent Chunk Management Engine (Base)                             | c2me-base                                             | 0.2.0+alpha.9.12             |
		|     7 | Concurrent Chunk Management Engine (Client/Uncap View Distance)       | c2me-client-uncapvd                                   | 0.2.0+alpha.9.12             |
		|     0 | Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues)  | c2me-fixes-chunkio-threading-issues                   | 0.2.0+alpha.9.12             |
		|    62 | Concurrent Chunk Management Engine (Fixes/General/Threading Issues)   | c2me-fixes-general-threading-issues                   | 0.2.0+alpha.9.12             |
		|    25 | Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues)  | c2me-fixes-worldgen-threading-issues                  | 0.2.0+alpha.9.12             |
		|    26 | Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs)      | c2me-fixes-worldgen-vanilla-bugs                      | 0.2.0+alpha.9.12             |
		|    55 | Concurrent Chunk Management Engine (No Tick View Distance)            | c2me-notickvd                                         | 0.2.0+alpha.9.12             |
		|    58 | Concurrent Chunk Management Engine (Optimizations/Chunk Access)       | c2me-opts-chunk-access                                | 0.2.0+alpha.9.12             |
		|    15 | Concurrent Chunk Management Engine (Optimizations/Chunk IO)           | c2me-opts-chunkio                                     | 0.2.0+alpha.9.12             |
		|    94 | Concurrent Chunk Management Engine (Optimizations/General WorldGen)   | c2me-opts-worldgen-general                            | 0.2.0+alpha.9.12             |
		|    93 | Concurrent Chunk Management Engine (Optimizations/Math)               | c2me-opts-math                                        | 0.2.0+alpha.9.12             |
		|    63 | Concurrent Chunk Management Engine (Optimizations/Memory Allocations) | c2me-opts-allocs                                      | 0.2.0+alpha.9.12             |
		|    32 | Concurrent Chunk Management Engine (Optimizations/Scheduling)         | c2me-opts-scheduling                                  | 0.2.0+alpha.9.12             |
		|    41 | Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen)   | c2me-opts-worldgen-vanilla                            | 0.2.0+alpha.9.12             |
		|    19 | Concurrent Chunk Management Engine (Rewrites/Chunk IO)                | c2me-rewrites-chunkio                                 | 0.2.0+alpha.9.12             |
		|    28 | Concurrent Chunk Management Engine (Server Utils)                     | c2me-server-utils                                     | 0.2.0+alpha.9.12             |
		|    87 | Concurrent Chunk Management Engine (Threading/Lighting)               | c2me-threading-lighting                               | 0.2.0+alpha.9.12             |
		|    34 | Concurrent Chunk Management Engine (Threading/Scheduling)             | c2me-threading-scheduling                             | 0.2.0+alpha.9.12             |
		|    68 | Concurrent Chunk Management Engine (Threading/WorldGen)               | c2me-threading-worldgen                               | 0.2.0+alpha.9.12             |
		|    81 | Concurrent Chunk Management Engine (Threading/WorldGen)               | c2me-threading-chunkio                                | 0.2.0+alpha.9.12             |
		|     1 | CrowdinTranslate                                                      | crowdin-translate                                     | 1.4+1.19.3                   |
		|   112 | Custom Entity Models                                                  | cem                                                   | 0.7.1                        |
		|    21 | Detail Armor Bar                                                      | detailab                                              | 2.6.3+1.19.3-fabric          |
		|   122 | Drip Sounds                                                           | waterdripsound                                        | 1.19-0.3.1                   |
		|    36 | Dynamic FPS                                                           | dynamicfps                                            | 2.2.0                        |
		|     4 | Eating Animation                                                      | eatinganimationid                                     | 1.9.1                        |
		|   158 | Entity Texture Features                                               | entity_texture_features                               | 4.2.0.1                      |
		|    43 | EntityCulling-Fabric                                                  | entityculling                                         | 1.5.2-mc1.19.3               |
		|    50 | Exordium                                                              | exordium                                              | 1.0.3-mc1.19.3               |
		|   167 | Fabric Language Kotlin                                                | fabric-language-kotlin                                | 1.8.7+kotlin.1.7.22          |
		|   129 | Falling Leaves                                                        | fallingleaves                                         | 1.14.2+1.19.3                |
		|   124 | Fast Load                                                             | fastload                                              | 2.6.7                        |
		|   207 | FerriteCore                                                           | ferritecore                                           | 5.1.0                        |
		|   203 | Inventory HUD +                                                       | inventoryhud                                          | 3.4.7                        |
		|    99 | Java HotSpot(TM) 64-Bit Server VM                                     | java                                                  | 17                           |
		|   141 | Kirin UI                                                              | kirin                                                 | 1.13.2                       |
		|    20 | Krypton                                                               | krypton                                               | 0.2.1                        |
		|    78 | LazyDFU                                                               | lazydfu                                               | 0.1.3                        |
		|   115 | LibZoomer                                                             | libzoomer                                             | 0.5.1+1.19.3                 |
		|   126 | Lithium                                                               | lithium                                               | 0.10.4                       |
		|   125 | MAmbience                                                             | mambience                                             | 5.2.1+1.19.3                 |
		|    33 | MidnightLib                                                           | midnightlib                                           | 1.1.0                        |
		|   136 | Minecraft                                                             | minecraft                                             | 1.19.3                       |
		|    49 | MixinExtras                                                           | com_github_llamalad7_mixinextras                      | 0.1.1                        |
		|   107 | Mod Menu                                                              | modmenu                                               | 5.0.2                        |
		|   118 | More Culling                                                          | moreculling                                           | 1.19.3-0.12.3                |
		|    59 | MoreChatHistory                                                       | morechathistory                                       | 1.1.1                        |
		|    64 | Mouse Wheelie                                                         | mousewheelie                                          | 1.10.6+mc1.19.3              |
		|   139 | No Chat Reports                                                       | nochatreports                                         | 1.19.3-v1.19.0               |
		|   108 | No Telemetry                                                          | no-telemetry                                          | 1.5.0                        |
		|    39 | NotEnoughAnimations                                                   | notenoughanimations                                   | 1.6.2                        |
		|   155 | Ok Zoomer                                                             | ok_zoomer                                             | 5.0.0-beta.10+1.19.3         |
		|    42 | OmegaConfig                                                           | omega-config                                          | 1.2.3-1.18.1                 |
		|   210 | Presence Footsteps                                                    | presencefootsteps                                     | 1.7.1                        |
		|   144 | Quilt Advancement API                                                 | quilt_advancement                                     | 4.0.0-beta.2+1.19.3          |
		|   163 | Quilt Base API                                                        | quilt_base                                            | 4.0.0-beta.2+1.19.3          |
		|   174 | Quilt Biome API                                                       | quilt_biome                                           | 4.0.0-beta.2+1.19.3          |
		|   142 | Quilt Block Content Registry API                                      | quilt_block_content_registry                          | 4.0.0-beta.2+1.19.3          |
		|   160 | Quilt Block Entity API                                                | quilt_block_entity                                    | 4.0.0-beta.2+1.19.3          |
		|   102 | Quilt Block Extensions API                                            | quilt_block_extensions                                | 4.0.0-beta.2+1.19.3          |
		|   173 | Quilt Client Command API                                              | quilt_client_command                                  | 4.0.0-beta.2+1.19.3          |
		|   148 | Quilt Command API                                                     | quilt_command                                         | 4.0.0-beta.2+1.19.3          |
		|   120 | Quilt Crash Info                                                      | quilt_crash_info                                      | 4.0.0-beta.2+1.19.3          |
		|   106 | Quilt Dimension API                                                   | quilt_dimension                                       | 4.0.0-beta.2+1.19.3          |
		|   113 | Quilt Entity API                                                      | quilt_entity                                          | 4.0.0-beta.2+1.19.3          |
		|   137 | Quilt Entity Events                                                   | quilt_entity_events                                   | 4.0.0-beta.2+1.19.3          |
		|   154 | Quilt Entity Networking API                                           | quilt_entity_networking                               | 4.0.0-beta.2+1.19.3          |
		|   145 | Quilt Item Content Registry API                                       | quilt_item_content_registry                           | 4.0.0-beta.2+1.19.3          |
		|   114 | Quilt Item Extension API                                              | quilt_item_extension                                  | 4.0.0-beta.2+1.19.3          |
		|    96 | Quilt Item Setting API                                                | quilt_item_setting                                    | 4.0.0-beta.2+1.19.3          |
		|   195 | Quilt Lifecycle Events                                                | quilt_lifecycle_events                                | 4.0.0-beta.2+1.19.3          |
		|   175 | Quilt Loader                                                          | quilt_loader                                          | 0.17.8                       |
		|   100 | Quilt Multipart Entity API                                            | quilt_entity_multipart                                | 4.0.0-beta.2+1.19.3          |
		|   187 | Quilt Networking                                                      | quilt_networking                                      | 4.0.0-beta.2+1.19.3          |
		|   164 | Quilt Points of Interest                                              | quilt_points_of_interest                              | 4.0.0-beta.2+1.19.3          |
		|   191 | Quilt Recipe API                                                      | quilt_recipe                                          | 4.0.0-beta.2+1.19.3          |
		|   180 | Quilt Registry API                                                    | quilt_registry                                        | 4.0.0-beta.2+1.19.3          |
		|   172 | Quilt Registry Entry Attachment                                       | quilt_registry_entry_attachment                       | 4.0.0-beta.2+1.19.3          |
		|   184 | Quilt Resource Loader                                                 | quilt_resource_loader                                 | 4.0.0-beta.2+1.19.3          |
		|   181 | Quilt Screen API                                                      | quilt_screen                                          | 4.0.0-beta.2+1.19.3          |
		|   198 | Quilt Status Effect API                                               | quilt_status_effect                                   | 4.0.0-beta.2+1.19.3          |
		|   194 | Quilt Surface Rule API                                                | quilt_surface_rule                                    | 4.0.0-beta.2+1.19.3          |
		|   183 | Quilt Tags API                                                        | quilt_tags                                            | 4.0.0-beta.2+1.19.3          |
		|   134 | Quilt Tooltip API                                                     | quilt_tooltip                                         | 4.0.0-beta.2+1.19.3          |
		|   156 | Quilt Vehicle API                                                     | quilt_vehicle                                         | 4.0.0-beta.2+1.19.3          |
		|   109 | Quilt Villager API                                                    | quilt_villager                                        | 4.0.0-beta.2+1.19.3          |
		|   188 | Quilted Fabric API                                                    | quilted_fabric_api                                    | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   170 | Quilted Fabric API Base                                               | quilted_fabric_api_base                               | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   177 | Quilted Fabric API Lookup API (v1)                                    | quilted_fabric_api_lookup_api_v1                      | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   169 | Quilted Fabric Biome API (v1)                                         | quilted_fabric_biome_api_v1                           | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   200 | Quilted Fabric Block API (v1)                                         | quilted_fabric_block_api_v1                           | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   208 | Quilted Fabric BlockRenderLayer Registration (v1)                     | quilted_fabric_blockrenderlayer_v1                    | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   143 | Quilted Fabric Client Tags                                            | quilted_fabric_client_tags_api_v1                     | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   152 | Quilted Fabric Command API (v1)                                       | quilted_fabric_command_api_v1                         | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   153 | Quilted Fabric Command API (v2)                                       | quilted_fabric_command_api_v2                         | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   104 | Quilted Fabric Commands (v0)                                          | quilted_fabric_commands_v0                            | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   161 | Quilted Fabric Containers (v0)                                        | quilted_fabric_containers_v0                          | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   204 | Quilted Fabric Content Registries (v0)                                | quilted_fabric_content_registries_v0                  | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   111 | Quilted Fabric Convention Tags API (v1)                               | quilted_fabric_convention_tags_api_v1                 | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   101 | Quilted Fabric Crash Report Info (v1)                                 | quilted_fabric_crash_report_info_v1                   | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   121 | Quilted Fabric Data Generation API (v1)                               | quilted_fabric_data_generation_api_v1                 | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   130 | Quilted Fabric Dimensions API (v1)                                    | quilted_fabric_dimensions_v1                          | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   162 | Quilted Fabric Entity Events (v1)                                     | quilted_fabric_entity_events_v1                       | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   133 | Quilted Fabric Events Interaction (v0)                                | quilted_fabric_events_interaction_v0                  | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   117 | Quilted Fabric Events Lifecycle (v0)                                  | quilted_fabric_events_lifecycle_v0                    | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   149 | Quilted Fabric Game Rule API (v1)                                     | quilted_fabric_game_rule_api_v1                       | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   166 | Quilted Fabric Item API (v1)                                          | quilted_fabric_item_api_v1                            | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   146 | Quilted Fabric Item Group API (v1)                                    | quilted_fabric_item_group_api_v1                      | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   209 | Quilted Fabric Key Binding API (v1)                                   | quilted_fabric_key_binding_api_v1                     | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   138 | Quilted Fabric Key Bindings (v0)                                      | quilted_fabric_keybindings_v0                         | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   123 | Quilted Fabric Lifecycle Events (v1)                                  | quilted_fabric_lifecycle_events_v1                    | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   193 | Quilted Fabric Loot API (v2)                                          | quilted_fabric_loot_api_v2                            | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|    97 | Quilted Fabric Loot Tables (v1)                                       | quilted_fabric_loot_tables_v1                         | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   116 | Quilted Fabric Message API (v1)                                       | quilted_fabric_message_api_v1                         | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   206 | Quilted Fabric Mining Level API (v1)                                  | quilted_fabric_mining_level_api_v1                    | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   168 | Quilted Fabric Models (v0)                                            | quilted_fabric_models_v0                              | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   150 | Quilted Fabric Networking (v0)                                        | quilted_fabric_networking_v0                          | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   147 | Quilted Fabric Networking API (v1)                                    | quilted_fabric_networking_api_v1                      | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   110 | Quilted Fabric Object Builder API (v1)                                | quilted_fabric_object_builder_api_v1                  | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   205 | Quilted Fabric Particles (v1)                                         | quilted_fabric_particles_v1                           | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   135 | Quilted Fabric Registry Sync (v0)                                     | quilted_fabric_registry_sync_v0                       | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   176 | Quilted Fabric Renderer - Indigo                                      | quilted_fabric_renderer_indigo                        | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|    98 | Quilted Fabric Renderer API (v1)                                      | quilted_fabric_renderer_api_v1                        | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   151 | Quilted Fabric Renderer Registries (v1)                               | quilted_fabric_renderer_registries_v1                 | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   127 | Quilted Fabric Rendering (v0)                                         | quilted_fabric_rendering_v0                           | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   128 | Quilted Fabric Rendering (v1)                                         | quilted_fabric_rendering_v1                           | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   157 | Quilted Fabric Rendering Data Attachment (v1)                         | quilted_fabric_rendering_data_attachment_v1           | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   179 | Quilted Fabric Rendering Fluids (v1)                                  | quilted_fabric_rendering_fluids_v1                    | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   103 | Quilted Fabric Resource Conditions API (v1)                           | quilted_fabric_resource_conditions_api_v1             | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   196 | Quilted Fabric Resource Loader (v0)                                   | quilted_fabric_resource_loader_v0                     | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   201 | Quilted Fabric Screen API (v1)                                        | quilted_fabric_screen_api_v1                          | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   189 | Quilted Fabric Screen Handler API (v1)                                | quilted_fabric_screen_handler_api_v1                  | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   190 | Quilted Fabric Sound API (v1)                                         | quilted_fabric_sound_api_v1                           | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   185 | Quilted Fabric Transfer API (v1)                                      | quilted_fabric_transfer_api_v1                        | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|   178 | Quilted Fabric Transitive Access Wideners (v1)                        | quilted_fabric_transitive_access_wideners_v1          | 5.0.0-alpha.5+0.68.1-1.19.3  |
		|    48 | Satin                                                                 | satin                                                 | 1.10.0                       |
		|    69 | Shulker Box Tooltip                                                   | shulkerboxtooltip                                     | 3.2.4+1.19.3                 |
		|   197 | Simple RPC                                                            | simple-rpc                                            | 3.2.1                        |
		|    89 | Smooth Boot                                                           | smoothboot                                            | 1.19-1.7.1                   |
		|   202 | SpruceUI                                                              | spruceui                                              | 4.1.0+1.19.3                 |
		|   131 | Starlight                                                             | starlight                                             | 1.1.1+fabric.ae22326         |
		|   182 | ToolTip Fix                                                           | tooltipfix                                            | 1.1.1-1.19.3                 |
		|    46 | Visuality                                                             | visuality                                             | 0.6.0                        |
		|   159 | VulkanMod                                                             | vulkanmod                                             | 0.2.0+2                      |
		|    79 | WaveyCapes                                                            | waveycapes                                            | 1.2.2                        |
		|   199 | YetAnotherConfigLib                                                   | yet-another-config-lib                                | 2.1.1                        |
		|    23 | asyncutil                                                             | com_ibm_async_asyncutil                               | 0.1.0                        |
		|    16 | atomicfu-jvm                                                          | org_jetbrains_kotlinx_atomicfu-jvm                    | 0.18.5                       |
		|    84 | cloth-basic-math                                                      | cloth-basic-math                                      | 0.6.1                        |
		|   192 | completeconfig-base                                                   | completeconfig-base                                   | 2.2.0                        |
		|    37 | completeconfig-gui-cloth                                              | completeconfig-gui-cloth                              | 2.2.0                        |
		|    44 | conditional mixin                                                     | conditional-mixin                                     | 0.3.2                        |
		|    17 | config                                                                | com_typesafe_config                                   | 1.4.2                        |
		|    77 | configurate-core                                                      | org_spongepowered_configurate-core                    | 4.1.2                        |
		|    47 | configurate-hocon                                                     | org_spongepowered_configurate-hocon                   | 4.1.2                        |
		|    76 | core                                                                  | com_electronwill_night-config_core                    | 3.6.5                        |
		|    95 | exp4j                                                                 | net_objecthunter_exp4j                                | 0.4.8                        |
		|    71 | geantyref                                                             | io_leangen_geantyref_geantyref                        | 1.3.13                       |
		|    11 | httpmime                                                              | org_apache_httpcomponents_httpmime                    | 4.5.10                       |
		|    67 | kotlin-reflect                                                        | org_jetbrains_kotlin_kotlin-reflect                   | 1.7.22                       |
		|    53 | kotlin-stdlib                                                         | org_jetbrains_kotlin_kotlin-stdlib                    | 1.7.22                       |
		|    10 | kotlin-stdlib-jdk7                                                    | org_jetbrains_kotlin_kotlin-stdlib-jdk7               | 1.7.22                       |
		|    13 | kotlin-stdlib-jdk8                                                    | org_jetbrains_kotlin_kotlin-stdlib-jdk8               | 1.7.22                       |
		|    38 | kotlinx-coroutines-core-jvm                                           | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm     | 1.6.4                        |
		|    65 | kotlinx-coroutines-jdk8                                               | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8         | 1.6.4                        |
		|    30 | kotlinx-datetime-jvm                                                  | org_jetbrains_kotlinx_kotlinx-datetime-jvm            | 0.4.0                        |
		|    45 | kotlinx-serialization-cbor-jvm                                        | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm  | 1.4.1                        |
		|    74 | kotlinx-serialization-core-jvm                                        | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm  | 1.4.1                        |
		|     2 | kotlinx-serialization-json-jvm                                        | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm  | 1.4.1                        |
		|     8 | lwjgl                                                                 | org_lwjgl_lwjgl_natives-linux                         | 3.3.1                        |
		|    72 | lwjgl                                                                 | org_lwjgl_lwjgl                                       | 3.3.1                        |
		|    88 | lwjgl                                                                 | org_lwjgl_lwjgl_natives-windows                       | 3.3.1                        |
		|    61 | lwjgl-glfw                                                            | org_lwjgl_lwjgl-glfw_natives-linux                    | 3.3.1                        |
		|    73 | lwjgl-glfw                                                            | org_lwjgl_lwjgl-glfw_natives-windows                  | 3.3.1                        |
		|    83 | lwjgl-glfw                                                            | org_lwjgl_lwjgl-glfw                                  | 3.3.1                        |
		|    51 | lwjgl-openal                                                          | org_lwjgl_lwjgl-openal_natives-linux                  | 3.3.1                        |
		|    70 | lwjgl-openal                                                          | org_lwjgl_lwjgl-openal                                | 3.3.1                        |
		|    85 | lwjgl-openal                                                          | org_lwjgl_lwjgl-openal_natives-windows                | 3.3.1                        |
		|     3 | lwjgl-shaderc                                                         | org_lwjgl_lwjgl-shaderc                               | 3.3.1                        |
		|    31 | lwjgl-shaderc                                                         | org_lwjgl_lwjgl-shaderc_natives-windows               | 3.3.1                        |
		|    52 | lwjgl-shaderc                                                         | org_lwjgl_lwjgl-shaderc_natives-linux                 | 3.3.1                        |
		|     5 | lwjgl-stb                                                             | org_lwjgl_lwjgl-stb_natives-linux                     | 3.3.1                        |
		|    57 | lwjgl-stb                                                             | org_lwjgl_lwjgl-stb_natives-windows                   | 3.3.1                        |
		|    92 | lwjgl-stb                                                             | org_lwjgl_lwjgl-stb                                   | 3.3.1                        |
		|     9 | lwjgl-vma                                                             | org_lwjgl_lwjgl-vma                                   | 3.3.1                        |
		|    29 | lwjgl-vma                                                             | org_lwjgl_lwjgl-vma_natives-linux                     | 3.3.1                        |
		|    60 | lwjgl-vma                                                             | org_lwjgl_lwjgl-vma_natives-windows                   | 3.3.1                        |
		|    27 | lwjgl-vulkan                                                          | org_lwjgl_lwjgl-vulkan                                | 3.3.1                        |
		|   132 | memory Leak Fix                                                       | memoryleakfix                                         | 1.19.3-0.7.0                 |
		|    90 | occlusionculling                                                      | com_logisticscraft_occlusionculling                   | 0.0.6-SNAPSHOT               |
		|    14 | simple-rpc-common                                                     | me_hypherionmc_simplerpc_simple-rpc-common            | 4.2.10                       |
		|    66 | threadly                                                              | org_threadly_threadly                                 | 7.0                          |
		|    91 | toml                                                                  | com_electronwill_night-config_toml                    | 3.6.5                        |
		|    54 | toml4j                                                                | com_moandjiezana_toml_toml4j                          | 0.7.2                        |
		|    35 | tweed4_annotated                                                      | tweed4_annotated                                      | 1.3.1+mc1.19.3               |
		|    56 | tweed4_base                                                           | tweed4_base                                           | 1.7.1+mc1.19.3               |
		|    40 | tweed4_data                                                           | tweed4_data                                           | 1.2.1+mc1.19.3               |
		|    75 | tweed4_data_hjson                                                     | tweed4_data_hjson                                     | 1.1.1+mc1.19.3               |
		|    22 | tweed4_tailor_coat                                                    | tweed4_tailor_coat                                    | 1.1.3+mc1.19.3               |
		|     6 | tweed4_tailor_screen                                                  | tweed4_tailor_screen                                  | 1.1.3+mc1.19.3               |
		|    24 | velocity-native                                                       | com_velocitypowered_velocity-native                   | 3.1.2-SNAPSHOT               |
		|------:|-----------------------------------------------------------------------|-------------------------------------------------------|------------------------------|
		
	Launched Version: 1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thank you very much for reporting this issue. Curseforge is down at the moment, you can get the newest version here for now: https://modrinth.com/mod/enhancedvisuals
