### ISSUE TITLE
the blood does not appear on the screen when I use the First Aid mod

### ISSUE THREAD

**Issue by JoshivaYzair** [CreativeMD/EnhancedVisuals#107]
when a monster hits me, the blood doesn't show on the screen

Forge: 1.19.2-43.2.3
EV Mod: 1.5.9 1.19.2
First Aid mod: 1.12.0 1.19.2

Default settings

**Comment by CreativeMD** [comment]
Are you on a server or singleplayer?

**Comment by JoshivaYzair** [comment]
Singleplayer

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. I don't think there is anything I can do at the moment. I don't know how FirstAid works and why EnhancedVisuals does not get notified if there is damage.
