### ISSUE TITLE
When using sodium,the screen goes dark when the screen blurs

### ISSUE THREAD

**Issue by NicoTheIdiot** [CreativeMD/EnhancedVisuals#108]
Basically the problem that everyone has on optifine,but on sodium. I don't use sodium extra,can you tell me what option I should change? thank you.

Fabric 1.19.2

**Comment by CreativeMD** [comment]
No idea ... maybe sodium disables the shader? Optifine does it as well if certain configurations are enabled. Maybe go through the settings of sodium and see if you can fix it.

**Comment by CreativeMD** [comment]
I tried it out with the newest version of EnhancedVisuals and it works just fine. Maybe it did not work earlier and the newest version fixed it. Used 1.19.3.

**Comment by xNicklaj** [comment]
This issue is still ongoing with the latest versions

**Comment by CreativeMD** [comment]
@xNicklaj what version are you using?

**Comment by xNicklaj** [comment]
I justed noticed the message, sorry for not replying earlier.
I'm using version 1.6.9, but I noticed this only happens with shaders, so it may not be this mod's fault.
