### ISSUE TITLE
You fixed the scaling, but now other mod's scaling is broken

### ISSUE THREAD

**Issue by DeshiDesu** [CreativeMD/EnhancedVisuals#109]
EnhancedVisuals_FORGE_v1.6.1_mc1.18.2.jar
Forge 40.2.0
Minecraft 1.18.2

Mods like Jade, ItemPhysic Full GUI appear smaller than they should be. Creative mode does not apply.
![Screenshot from 2023-01-18 21-55-46](https://user-images.githubusercontent.com/120287925/213346511-d675c20a-16a2-4886-b8b2-e4e03b349c58.png)
![Screenshot from 2023-01-18 21-56-05](https://user-images.githubusercontent.com/120287925/213346515-1edd94b0-f9aa-420e-a0b2-dfa261a10cec.png)
![Screenshot from 2023-01-18 21-56-18](https://user-images.githubusercontent.com/120287925/213346516-7f3f379e-1122-4b88-90d2-f18b82e13321.png)
![Screenshot from 2023-01-18 21-58-00](https://user-images.githubusercontent.com/120287925/213346517-09063b29-589d-4427-b6ab-7fd60feb98e1.png)
![Screenshot from 2023-01-18 22-06-48](https://user-images.githubusercontent.com/120287925/213346520-a40c92ee-da6a-4988-9ee0-8ec3375c70a6.png)

**Comment by CreativeMD** [comment]
Oh right. Thanks for letting me know! It's fixed in the newest version.

**Comment by DeshiDesu** [comment]
thanks
