### ISSUE TITLE
Please Find a Solution to This

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#11]
PLEASE. 
![gui](https://cloud.githubusercontent.com/assets/24831406/22893126/8c121a4a-f21d-11e6-9a67-7d4877894925.PNG)
it should be my gui in fact. but...

**Comment by CreativeMD** [comment]
This is intended, you should not be able to pause the game to gain any advantage. Besides effects will fade away in the main menu.
