### ISSUE TITLE
The scaling is fixed, but now the GUI is flipped

### ISSUE THREAD

**Issue by DeshiDesu** [CreativeMD/EnhancedVisuals#110]
EnhancedVisuals_FORGE_v1.6.2_mc1.18.2.jar
Forge 40.2.0
Minecraft 1.18.2

The Jade GUI is inverted horizontally (Look at hotbar) and certain GUI text/features do not appear. Creative mode is normal as always.
![2023-01-19_10 17 59](https://user-images.githubusercontent.com/120287925/213483434-a48e97dd-c90f-41aa-8b53-bcfa45b4e9ae.png)
![2023-01-19_10 18 30](https://user-images.githubusercontent.com/120287925/213483445-ef941781-08e2-4900-9574-86a30d7521f7.png)
![2023-01-19_10 18 45](https://user-images.githubusercontent.com/120287925/213483453-816ee74c-2459-442a-9893-674e45ce0a1d.png)
![2023-01-19_10 25 31](https://user-images.githubusercontent.com/120287925/213483456-6be4ce49-f146-48c6-9dd4-2708047c4b57.png)
![2023-01-19_10 25 59](https://user-images.githubusercontent.com/120287925/213483458-a653df2e-84b1-46b7-9a84-c333b602e3a7.png)

**Comment by DeshiDesu** [comment]
Not sure if this is only on my part. You've done testing on this, have you?

**Comment by CreativeMD** [comment]
I have, but on 1.19 not 1.18. The newest version should fix this issue: https://modrinth.com/mod/enhancedvisuals/version/1.6.3
I'm really sorry for all the trouble. I forgot that things work a little different in 1.18 ...

**Comment by DeshiDesu** [comment]
Np, thanks for your hard work and dedication as always

**Comment by CreativeMD** [comment]
Does it work now?

**Comment by DeshiDesu** [comment]
Yes it works beautifully. Sorry for the late response!
