### ISSUE TITLE
Is this required on server?

### ISSUE THREAD

**Issue by TheeMrCheeky** [CreativeMD/EnhancedVisuals#111]
is this required on server as well? cause i don't get blood splatter when on server 1.19.3 & latest ver. of this mod

**Comment by DeshiDesu** [comment]
![image](https://user-images.githubusercontent.com/120287925/213602678-9b83d23c-4249-4c63-a1c3-b0533bac6fd5.png)

**Comment by TheeMrCheeky** [comment]
oh okay sorry didn't read comments jsut checked description
