### ISSUE TITLE
Weird issue when changing some settings.

### ISSUE THREAD

**Issue by DBPT210** [CreativeMD/EnhancedVisuals#112]
So I was trying to change some settings in-game and this thing was always happening. I wanted to change the intensity of the heartbeat visual affect while keeping the red aura but this kept happening. I don't know if this is the mod or another thing messing with it. I also tried setting outside the game and restarting it, but no luck.

[Here is a video](https://www.youtube.com/watch?v=b_x3gnFqSr0) (file too big sorry)

I'll also include the log file if that helps.
[latest.log](https://github.com/CreativeMD/EnhancedVisuals/files/10903204/latest.log)

**Comment by CreativeMD** [comment]
Does deleting your config file help (also make sure to shutdown minecraft first)? Sorry for not responding earlier.

**Comment by CreativeMD** [comment]
Will close this due to inactivity.
