### ISSUE TITLE
Death Message Bug

### ISSUE THREAD

**Issue by bunnypause** [CreativeMD/EnhancedVisuals#113]
First, thank you for developing this mod. It has greatly improved my playing experience <3

Second, I've sadly encountered this bug out of nowhere where taking any kind of damage displays a bugged death message like "fall,player hit the ground too hard" whenever i take fall damage, for example. Here's a video in case it's needed!
[https://youtu.be/ThpGKSa_zNs](url)

Using latest version of mod for fabric 1.19.2, havent uninstalled or installed anything.
Thank you in advance!

**Comment by CreativeMD** [comment]
Use the command /cmdclientconfig and disable damage debug. Not sure where exactly the config is located, but you should be able to find it.

**Comment by bunnypause** [comment]
Thank you so much!!
