### ISSUE TITLE
Compatiblty with Thirst Was Taken

### ISSUE THREAD

**Issue by Blunder-G** [CreativeMD/EnhancedVisuals#114]
[Thirst Was Taken](https://www.curseforge.com/minecraft/mc-mods/thirst-was-taken) is a well designed thirst mod. It only adds one thing, thirst mechanic. As in Tough As Nails, it would be a nice feature if the screen became sharper/blurred when the water bar is low

**Comment by CreativeMD** [comment]
I do not support 1.19.2 anymore. If this mod updates to 1.19.4 you can notify me again and I will add compatibility. I will close this issue for now, but you can reply here and I will see it.

**Comment by MoonsMess** [comment]
Thirst Was Taken now supports 1.20.1 and this would still be a great feature

**Comment by CreativeMD** [comment]
@IDonutKnowYT I will try to add it, already contacted the author to figure out a good way to do so.

**Comment by CreativeMD** [comment]
Added support for it in the newest version. Would be happy if you could try it out. Maybe you have to tweak the values a bit. If yes let me know what settings you came up with (so I can make them the default).

**Comment by CreativeMD** [comment]
Oh wait, I thought this was about ColdSweat. Actually the support for Thirst Was Taken is still not there.

**Comment by CreativeMD** [comment]
I will close this issue here. I don't think this will ever happen, unless the author responds in the other issue.
