### ISSUE TITLE
(Suggestion) Rain/Leaving water droplets

### ISSUE THREAD

**Issue by GibbyGibbon** [CreativeMD/EnhancedVisuals#115]
Add new visuals for water droplets on screen, flowing downwards. Appearing on top, disappearing on the bottom or mid screen?
With max 2-3 droplets at the same time not to clutter the creen. WIth about 20-40% opactity.
 Activating when: 
1. character is under rain/snow particles 
2. characters head is leaving water

**Comment by CreativeMD** [comment]
I could add some particles for that, but it will not look that pretty. Maybe I go for some blurry once? If you send me a few good looking textures I will add it.

**Comment by GibbyGibbon** [comment]
Blurry ones sounds good. Could be like 4 pixels sliding down, leaving a slowly disappearing trail, something simple. Fancy textures could impaire the player vision too much :)

**Comment by CreativeMD** [comment]
Send me these simple textures please :D

**Comment by GibbyGibbon** [comment]
How can i send you these textures?

**Comment by CreativeMD** [comment]
You can send it here (copy the image and paste it in, it will be uploaded to github and shown soon after) or via discord. It's up to you.

**Comment by GibbyGibbon** [comment]
![droplet 8](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/d538d352-0924-4269-ad3b-f2727830f281)
![droplet 7](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/4b3b3711-23ca-4e38-904c-13a4ffe5c2e5)
![droplet 6](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/05990c17-f28f-42c8-b34b-266a0ea4b43a)
![droplet 10](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/15692388-3edd-4380-aa21-a3dc386019b9)
![droplet 5](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/445e1329-5ec5-4d93-a7c1-f927f01601ee)
![droplet 4](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/ff053497-1f15-42fe-b072-53912ea678b2)
![droplet 3](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/9ba95b39-e63e-47bd-ae73-04102f52b465)
![droplet 2](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/f443e172-ac58-4aff-a4d0-4f28aa1b12a5)
![droplet 1](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/232aae30-96bd-4758-9e26-0220f097e127)
![trail white](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/16b49227-6813-4464-b966-14e192e4ede5)
![trail blue](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/9b8dd875-9dc1-493d-82a0-3e63e74f4715)
![droplet big 3](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/33bb6f11-62ec-44bd-9ba9-0a7382428b71)
![droplet big 2](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/d55cf0da-2beb-4b52-8dbc-dff5e4ecf943)
![droplet big 1](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/dd552369-0811-410c-b2ac-78f6335aabb0)
![droplet 9](https://github.com/CreativeMD/EnhancedVisuals/assets/129335411/fc7519af-1e83-4c8e-bce9-7e70c5033ce4)

1. I think that bluring them would give better results (dont even know if they are good or bad, there are few different variants not quite fitting the rest).
2. If there is possiblity, the trail pixel could appear as soon as the droplet moves down, and stay for 3 ticks or so, fading away.
3. in addition trail pixels could appear at random or alternately, one to the left, three to the right, one blue and three white etc...

Its just an artistic vision xD. Would help with coding but got no clue about that magic.

P.S. textures might be too small, thell me how big you want them to be

**Comment by CreativeMD** [comment]
After such a long time I have finally managed to add a rain effect. I have no used your textures. I took a different approach. Let me know what you think about it. New version is out. Thanks for taking the time, hope you are somehow satisfied with the result (unfortunately it is not as advanced as your suggestion).

**Comment by GibbyGibbon** [comment]
Lost MC from the radar a while ago. 'm astounded by Your determination. Hope that this effort gave you satisfaction and the addition will contribute, to help others praise your opus.
