### ISSUE TITLE
1.20 fabric not working (v1.6.4)

### ISSUE THREAD

**Issue by Arrocha08** [CreativeMD/EnhancedVisuals#117]
crashing:
![image](https://github.com/CreativeMD/EnhancedVisuals/assets/105840060/c1e4a3c5-e30e-4aaa-ae5d-3d2de4054265)

**Comment by CreativeMD** [comment]
Uploaded a new version of CreativeCore, which should fix it. If there are still issues please report it here and I will reopen this issue.
