### ISSUE TITLE
Cape renders on top of the player model

### ISSUE THREAD

**Issue by n643064** [CreativeMD/EnhancedVisuals#118]
The cape is rendered on top of the player model in the survival inventory, this also happens in creative mode when 'doEffectsInCreative' is set to true.
![cape and chest](https://github.com/CreativeMD/EnhancedVisuals/assets/80533058/bcfc3b53-efea-42f3-8a8f-18d3c34a0c0f)

Minecraft version: 1.20
Fabric loader version: 0.14.21
System: Linux 6.1.0-9-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.27-1
GPU: NVIDIA GeForce GTX 1650
Driver: nvidia 525.105.17
Mods:
 - Enhanced Visuals 1.6.4
 - Creative Core 2.10.23
 - Fabric API 0.83.0
 - Mod menu 7.0.1

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Thanks for reporting this issue.
