### ISSUE TITLE
Minecraft 1.20 crash with this mod

### ISSUE THREAD

**Issue by wilebaldo** [CreativeMD/EnhancedVisuals#119]
When I activate I have and error loading the game, I have minecraft 1.20 and I downloaded the mod versions 1.6.4 1.6.5 and 1.6.6 and is not matter witch one always is crash the game.

https://mclo.gs/JyPPA6u

**Comment by CreativeMD** [comment]
I have reuploaded 1.6.6, just download it again and it should be fixed. Thank you very much for reporting this issue! Sorry for the trouble.
