### ISSUE TITLE
Fabric 1.18.2 When the Creeper blowing up/damaged the player, the game will crash

### ISSUE THREAD

**Issue by NancalaStarry** [CreativeMD/EnhancedVisuals#121]
[crash-2023-07-08_17.04.40-client.txt](https://github.com/CreativeMD/EnhancedVisuals/files/11994325/crash-2023-07-08_17.04.40-client.txt)
[2023-07-08-4.log](https://github.com/CreativeMD/EnhancedVisuals/files/11994326/2023-07-08-4.log)

I use Enhanced Visuals (Fabric) 1.5.5

**Comment by NancalaStarry** [comment]
I tried to remove some mod to see if there was really a problem.
So when I remove Raise Sound Limit Simplified mod, it didn't crash as usually.
https://www.curseforge.com/minecraft/mc-mods/rsls

**Comment by CreativeMD** [comment]
Hey, I have dropped support for 1.18.2 quite a while ago. I have tried it out in 1.20 and had no issues. I guess the best way to fix it is to remove one of the mods or to update to 1.20. Sorry for the troubles :| Thanks for taking the time to report this issue!
