### ISSUE TITLE
[Suggestion-1.19.2] Compatible with one mod!

### ISSUE THREAD

**Issue by Qee1y** [CreativeMD/EnhancedVisuals#123]
Provide Enhanced Visuals compatibility for Cold Sweat mod and Third Was Taken mod。thank

**Comment by CreativeMD** [comment]
Sorry, but I already support `Survive` and `ToughAsNails`. Furthermore I do not support 1.19.2 anymore. If there is a popular mod in 1.20 I might add support. Just open another ticket then. Maybe these two mods are an option for you.
