### ISSUE TITLE
Visual bugs when using Lucky TNT Mod

### ISSUE THREAD

**Issue by PakoJones88** [CreativeMD/EnhancedVisuals#126]
Forge version:
1.18.2-40.2.17

Mods used:
CreativeCore_FORGE_v2.6.17_mc1.18.2
EnhancedVisuals_FORGE_v1.6.4_mc1.18.2
LuckyTNTMod-1.18.2-1.3.6

Issue:
The screen turns almost completely black when the heartbeat effect occurs and when getting underwater.

Screenshot:
![Heartbeat](https://github.com/CreativeMD/EnhancedVisuals/assets/110305970/3386d38b-9c05-416c-9341-2dc094eb150f)

**Comment by CreativeMD** [comment]
Sorry for responding incredible late. I unfortunately do not support 1.18.2. If this issue persists in 1.20.1 let me know, but till then I will close this issue.
