### ISSUE TITLE
Visual error

### ISSUE THREAD

**Issue by Sevenied** [CreativeMD/EnhancedVisuals#127]
![6c9776ca-7c89-48da-8077-93b16e75f369](https://github.com/CreativeMD/EnhancedVisuals/assets/130077711/a760789c-04d2-4bd5-be9c-90734a5f5b43)
The original color of this photo is blue, it's the sea. that's the kind of overexposure the mod gives.
Version 1.19.2

**Comment by CreativeMD** [comment]
This is during the loading screen? Are you sure that is related to EnhancedVisuals? Do you have to do something before to make this occur?

**Comment by Sevenied** [comment]
is the loading screen. The main menu screen has the same problem. No, all other mods are working fine and I have not found any confilicts.

**Comment by CreativeMD** [comment]
Sorry. I must have overlooked your response. I unfortunately dropped support for 1.19.2 quite some time ago. I don't see a way to fix it. You could go to config (using the command /cmdclientconfig) and see if you can disable certain effects to get rid of this issue. Besides that either remove EnhancedVisuals or try to update to a newer minecraft version.
