### ISSUE TITLE
Because curseforge was not logged in, the problem can only be described here.

### ISSUE THREAD

**Issue by Qee1y** [CreativeMD/EnhancedVisuals#129]
Whether it's explosion blur or water blur, it will cause a black screen.
 
Using Embeddium

forge 47.2.21
EnhancedVisuals_FORGE_v1.6.9_mc1.20.1

**Comment by CreativeMD** [comment]
You need to tweak the settings to allow for shaders to work. Not sure what setting exactly is necessary. I guess just try it out.
