### ISSUE TITLE
Client freeze when going into water

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/EnhancedVisuals#13]
As of EnhancedVisuals v1.0.12 mc1.9-1.10.jar, when entering water, the client screen gets blurry and freezes.
We can still here mobs moving around and eventually killing us. Once we're dead, no buttons shows up on screen, but from the sounds of it they're there.
There's no specifics in the logs.
Issue was reproduced on 3 different PCs using the same modpack https://minecraft.curseforge.com/projects/mage-wars/files .

**Comment by CreativeMD** [comment]
I will do some testing, maybe i can find what is causing the issue.

**Comment by CreativeMD** [comment]
Support for 1.10 has been dropped, if this problem still occurs using the newer versions, just reopen this issue.
