### ISSUE TITLE
Visual Error when vignette is disabled 

### ISSUE THREAD

**Issue by PopSikle23** [CreativeMD/EnhancedVisuals#130]
![image](https://github.com/CreativeMD/EnhancedVisuals/assets/88212115/93a45231-975e-436f-bcd7-ddfb9fe728ff)

**Comment by CreativeMD** [comment]
How can you disable vignette effect in vanilla minecraft?

**Comment by PopSikle23** [comment]
this is using proformance mod "Embeddium" and also on optimization mod "OptiFine" it has a setting to disable Vignette

**Comment by CreativeMD** [comment]
At moment I do not see a way to fix it. I have tried everything. Just keep the vignette enabled for the moment. I have contacted the authors of Embeddium, not sure if they have an idea.

**Comment by CreativeMD** [comment]
Took me quite some time to figure out, but I have figured out why the issue occurs. It is fixed in the newest version. Thanks for taking the time to report this issue.! Your hint about the vignette brought me on the right track.

**Comment by PopSikle23** [comment]
yippee thank you for fixing this :D
