### ISSUE TITLE
VIsual Error whenever youre low on health and screen starts blinking

### ISSUE THREAD

**Issue by PopSikle23** [CreativeMD/EnhancedVisuals#133]
https://github.com/CreativeMD/EnhancedVisuals/assets/88212115/f52011ce-0b19-42a9-afbf-05905c81777a

**Comment by CreativeMD** [comment]
What version of minecraft and EnhancedVisuals are you using?

**Comment by PopSikle23** [comment]
1.20.1 forge

**Comment by PopSikle23** [comment]
1.20.1 forge

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Thanks for reporting this issue!
