### ISSUE TITLE
Visual error when entering the water

### ISSUE THREAD

**Issue by Yoni664** [CreativeMD/EnhancedVisuals#134]
Sometimes it also occurs randomly even outside the water, but it is more common when entering the water or going outside. Heres a video of what Im talking about

https://github.com/CreativeMD/EnhancedVisuals/assets/143241985/d15b6431-2d5c-4041-bc6e-8ae4101bdfc5

**Comment by Yoni664** [comment]
I also checked that it is not a compatibility problem with any other mod but even using only Fabric Api, creative core and this mod the error still occurred. I almost forgot to say that Im playing on 1.20.1 Fabric 0.15.10 and the mod version is 1.7.0

https://github.com/CreativeMD/EnhancedVisuals/assets/143241985/a6cd38a1-df38-4125-8886-8b1c1f866821

**Comment by CreativeMD** [comment]
Thanks for reporting this issue and providing examples. Should be fixed in the newest version.
