### ISSUE TITLE
[Suggestion] Make texts on the death screen modifiable with resource packs

### ISSUE THREAD

**Issue by Yoni664** [CreativeMD/EnhancedVisuals#136]
Hi! I noticed that the mod adds funny texts on the death screen, I thought I could change them using some resource pack but when I opened the mod's jar file I noticed that it is not a text file. Doing a little more research, I discovered that it was more of a class file, which I decompiled and edited to see if I could change the texts to my native language (since I speak Spanish and I really wanted more personalized texts). Obviously it didn't work when compiling it, since I'm not a programmer and I have no idea how to compile the java file with all the dependencies that it has, which I assume are from creative core, but I still can't think of how to compile it. So my question is if there is a direct possibility that the text that appears on the death screen can be changed with resource packs

**Comment by CreativeMD** [comment]
You can change these death messages ingame. Using the command /cmdclientconfig. It is stored in the config file. It is not possible to modify it via a resourcepack.

**Comment by Yoni664** [comment]
thanks! Im gonna add a lot of messages lol
