### ISSUE TITLE
Too much blur

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/EnhancedVisuals#14]
As of EnhancedVisuals v1.0.12 mc1.9-1.10.jar, when player is low on hearth, the blur is way too intense to do anything in the game.
Can the blur be much more light?

**Comment by CreativeMD** [comment]
You can configure each effect and its intensity inside the config file.

**Comment by LemADEC** [comment]
I'm missing the option to adjust the number of hearts left that start triggering the effect.

Also, options are unclear to me, notably:
   # alpha = normalAlpha * alphaFactor [range: 0.0 ~ 1.0, default: 1.0]
    S:alphaFactor=1.0
=> does 0 mean no overlay at all?

    # heartbeat duration [range: 0.0 ~ 10000.0, default: 10.0]
    S:heartBeatDuration=10.0
=> is it the length of 1 flash or the delay between 2 flashes? is it measured in ticks or ms?

    # heartbeat intensity [range: 0.0 ~ 10000.0, default: 50.0]
    S:heartBeatIntensity=50.0
=> which intensity? is it the lighting intensity of the effect?

    # maximum additional splash duration [range: 0.0 ~ 10000.0, default: 30.0]
    S:splashAdditionalDuration=0.0
=> what's triggering the additional duration? is it always added?

**Comment by CreativeMD** [comment]
- yes, if you multiply a number by zero it will be zero.
- everything is measured in ticks
- the 'min' value will always be added. 'additional' is the maximum additional duration:
`min + additional * random()`
that would mean if we have the following values:
```
S:splashAdditionalDuration=30.0
S:splashMinIntensity=10.0
```
the duration of the splash effect will be from 10 ticks to 40 ticks long.
- Same goes for intensity. The higher the intensity the less you will be able to see (means screen gets even blurrier).
