### ISSUE TITLE
Compat Issue with latest Cold Sweat update

### ISSUE THREAD

**Issue by Smoker120900** [CreativeMD/EnhancedVisuals#140]
[crash-2024-05-31_19.09.05-client.txt](https://github.com/user-attachments/files/15519663/crash-2024-05-31_19.09.05-client.txt)
Hello, i contacted Cold Sweat's dev and they said to contact you because the issue was in EV, this is the crash.log

**Comment by CreativeMD** [comment]
Can you download the newest beta and see if that version works?

**Comment by senoqqq** [comment]
> Can you download the newest beta and see if that version works?

Where can I download the latest beta version? I downloaded the latest version from Modrinth, crashes when entering the world.

**Comment by CreativeMD** [comment]
@ZarsQv Can you send me the crash-report?

**Comment by senoqqq** [comment]
[crash-2024-06-19_01.35.14-client.txt](https://github.com/user-attachments/files/15892717/crash-2024-06-19_01.35.14-client.txt)

**Comment by CreativeMD** [comment]
Can you try out the newest beta version of ColdSweat? That should work.

**Comment by senoqqq** [comment]
> Can you try out the newest beta version of ColdSweat? That should work.

Yes, it works. Thanks!
