### ISSUE TITLE
How to reliably display the red effect when damaged?

### ISSUE THREAD

**Issue by KozukiYOMA** [CreativeMD/EnhancedVisuals#145]
How to reliably display the red effect when damaged?
I tried changing various configurations, but still there were times when it was not displayed.
I would like to know how to ensure that they are displayed.

**Comment by CreativeMD** [comment]
What version of Minecraft are you using?

**Comment by KozukiYOMA** [comment]
Fabric-0.16.0-1.21

**Comment by CreativeMD** [comment]
Reworked how the event is called, meaning the new version should hopefully fix your issue.
