### ISSUE TITLE
Add ignore wind charge to explosions?

### ISSUE THREAD

**Issue by Frey4SH** [CreativeMD/EnhancedVisuals#146]
more a suggestion than a bug, but it's kinda hard to use wind charges for using the mace or platforming currently and i think adding an option like ignore breeze for wind charges would be nice, something like "ignore wind charge"
maybe even just an "ignore self" option so other players can use it as a disrupt? i don't know if that's possible but it'd be fun

**Comment by CreativeMD** [comment]
Added this option in the newest version. Thanks for reporting this issue.
