### ISSUE TITLE
[1.21 Fabric] Upon accumulating sand particles on your screen and pressing esc, weird black boxes will appear in place of the sand.

### ISSUE THREAD

**Issue by cobaltlol2** [CreativeMD/EnhancedVisuals#147]
![image](https://github.com/user-attachments/assets/a6ff1204-37ca-4410-8d4d-5ebbc5ed91d0)

**Comment by CreativeMD** [comment]
This is a known issue. Unfortunately I have no idea how to fix it.

**Comment by cobaltlol2** [comment]
Sad

**Comment by cobaltlol2** [comment]
> This is a known issue. Unfortunately I have no idea how to fix it.

Not sure what I did, but it seems to have fixed on its own? Maybe I Removed some mod or smth idk

**Comment by CreativeMD** [comment]
Can you tell me which mod you removed? This might help me to figure out the case?

There is one way to fix and that is to remove the blur menu effect, but unfortunately there is nothing I can do about it.

**Comment by cobaltlol2** [comment]
> Can you tell me which mod you removed? This might help me to figure out the case?
> 
> There is one way to fix and that is to remove the blur menu effect, but unfortunately there is nothing I can do about it.

Sadly not sure, if you'd like to test, here's my modpack link on modrinth. I believe the glitch was still happening on one of the older versions, so you could find the fix that way maybe? https://modrinth.com/modpack/true-vanilla+

**Comment by CreativeMD** [comment]
Actually I had an idea how to fix it. The problem is vanilla itself and their way of rendering the blur effect. I just tweaked their rendering code in the newest version. Now it works fine. Thanks for taking the time to help out! Very much apricated. I hope things work now consistently for you.

**Comment by cobaltlol2** [comment]
> Actually I had an idea how to fix it. The problem is vanilla itself and their way of rendering the blur effect. I just tweaked their rendering code in the newest version. Now it works fine. Thanks for taking the time to help out! Very much apricated. I hope things work now consistently for you.

Your welcome 👍
