### ISSUE TITLE
[1.20.1 Forge] Crash on Startup

### ISSUE THREAD

**Issue by FakeRootBeer** [CreativeMD/EnhancedVisuals#148]
I am running the latest versions of CreativeCore, EnhancedVisuals, and Cold Sweat. Using both Cold Sweat and EnhancedVisuals causes the crash despite having compatibility.

**Comment by CreativeMD** [comment]
Can you send me the crash-report?

**Comment by MistifyedOne** [comment]
[crash-2024-08-08_19.33.13-client.txt](https://github.com/user-attachments/files/16555210/crash-2024-08-08_19.33.13-client.txt)

**Comment by Mqony** [comment]
@CreativeMD 
[crash-2024-08-08_19.33.13-client.txt](https://github.com/user-attachments/files/16555214/crash-2024-08-08_19.33.13-client.txt)

**Comment by CreativeMD** [comment]
Get the newest alpha/beta version from ColdSweat. This should fix your issue. Sorry for not responding earlier.
