### ISSUE TITLE
How to disable water drops on screen during rain? I'm using EnhancedVisuals_v1.4.4_mc1.12.2.jar

### ISSUE THREAD

**Issue by darchitectlp** [CreativeMD/EnhancedVisuals#149]
I can't find a setting to disable the raindrops in the config, but maybe I'm missing it. I dug through the jar looking for an image I could replace with a texture pack, but couldn't find anything there. The effect is simply too overwhelming. But thanks for a great mod! Really love the interaction with Tough as Nails.

**Comment by CreativeMD** [comment]
You have to use the command /cmdclientconfig there you can find all the configuration for the effects.

**Comment by darchitectlp** [comment]
It looks like the command is actually /cmdconfig, but even when that pops open the gui, I can't find an option for the raindrops covering the screen. Also, I don't see a config option in the .cfg file either (I far prefer editing a text file than digging through a gui):
![2024-08-06_18 07 50](https://github.com/user-attachments/assets/f05816ce-dfbe-48f2-9a65-669adb9aabf3)
<img width="631" alt="Screen Shot 2024-08-06 at 6 05 55 PM" src="https://github.com/user-attachments/assets/08184745-1755-4e42-a419-b939e81fb857">
<img width="637" alt="Screen Shot 2024-08-06 at 6 05 48 PM" src="https://github.com/user-attachments/assets/91faf0e1-cc91-48e9-8706-24666a0c7120">

**Comment by CreativeMD** [comment]
It's a client side configuration. That's why you need to use the command /cmdclientconfig. There is a way to force synchronization on client setting which is the screen you show in your pictures.

**Comment by darchitectlp** [comment]
Sorry for the late reply; haven't had a chance to play. /cmdclientconfig doesn't work. It just says "Unknown command." Can you just tell me which line controls the raindrops on the screen in "enhancedvisuals-client.json"? I don't see a line in there that indicates it might control the rain drop effect. Thanks.

Quick edit: just to be clear, you did see which version I'm using, yes? Just in case you added that feature in a later version.

**Comment by CreativeMD** [comment]
Oh sorry, I totally did not look closely. In 1.12.2 there is no rain effect from EnhancedVisuals. This must be another mod.
