### ISSUE TITLE
Please Disable Effects in Creative Mode

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#15]
/gamemode 1 should disable the effects. and i also see effects on Main Menu... it has no sense..

**Comment by CreativeMD** [comment]
I'm not really sure if it should be like that, i prefer to have effects even if i'm in creative. I will add a config option for it in the next version (might take one or two weeks)

**Comment by CreativeMD** [comment]
Is added in 1.1.0

**Comment by ghost** [comment]
thanks ^^
