### ISSUE TITLE
[1.12.2 Forge] Crash on Startup

### ISSUE THREAD

**Issue by Keksekkwoxox** [CreativeMD/EnhancedVisuals#150]
I have latest version of both CreativeCore and EnhancedVisuals. Game crashes while opening.
Here is the crash report:
[crash-2024-08-02_17.32.39-client.txt](https://github.com/user-attachments/files/16471959/crash-2024-08-02_17.32.39-client.txt)

**Comment by CreativeMD** [comment]
Update ItemPhysic as well then it should work.
