### ISSUE TITLE
minValue vs min

### ISSUE THREAD

**Issue by Rushmore75** [CreativeMD/EnhancedVisuals#151]
I'm messing around with the in-game config and I'm a bit confused on the `min` vs `minValue` (and `max` vs `maxValue`)

what's the difference between the two?
![image](https://github.com/user-attachments/assets/2f487211-f31f-4908-8a28-620c83cdda43)

**Comment by CreativeMD** [comment]
![image](https://github.com/user-attachments/assets/72dff2a6-26c4-4796-a9f3-20a45f2207bc)
Hope that explains it for you.
