### ISSUE TITLE
low health heartbeat effect is way, way, waaaaaay too intense by default

### ISSUE THREAD

**Issue by swedneck** [CreativeMD/EnhancedVisuals#155]
the default settings are so intense that it may well trigger epileptic seizures, and i have seen several other people complain about the effect being very uncomfortable.

IMO the blur is the big culprit, that should be lowered to honestly something like 10% of the current default.  

For modpacks including this mod, i'm all but certain that some people have tossed it in the trash when this effect came up and they couldn't figure out how to disable it.

**Comment by CreativeMD** [comment]
You can configure everything using the command /cmdclientconfig. There you can disable the effect, tweak the intensity. Hope that works for you.

**Comment by swedneck** [comment]
that doesn't solve the issue though, you're just expecting everyone who (understandably) finds this uncomfortable to go out of their way to find out which mod causes it, how to configure it, and what to change.

it shouldn't be difficult to just change the default values to something that works for everyone, expecting people to change it themselves just alienates users.

**Comment by CreativeMD** [comment]
I cannot speak for modpacks that are using this mods. They can obviously change the config as they please. By default it is quite intense because that is the purpose of this mod. I can see that some don't like it ... that's why there are plenty of settings to change stuff.
