### ISSUE TITLE
A strange effect on the player miniature when I open the inventory.

### ISSUE THREAD

**Issue by wilebaldo** [CreativeMD/EnhancedVisuals#157]
This is very strange effect, I test all my mods and the problem is with this one, but this happening only with the version of the mod 1.8.8, I tested all the previews one and is working on.

Let me show you some pictures so you can see the visual error.

this is with the version 1.8.8
![2024-08-25_10 41 34](https://github.com/user-attachments/assets/6c522b2f-4c1e-41ce-aedc-363dfe782888)

this is with the version 1.8.7
![2024-08-25_10 51 38](https://github.com/user-attachments/assets/ccbc9272-edb9-45ee-aa47-d4f81052f6c5)

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Thank you very much for reporting this issue!
