### ISSUE TITLE
Incompatible with Blur+ mod since version 1.8.8

### ISSUE THREAD

**Issue by WingFrosty** [CreativeMD/EnhancedVisuals#158]
Since version 1.8.8 I've been having problems in player model displaying within the inventory when using armor.

Versions 1.8.8/1.8.9
![image](https://github.com/user-attachments/assets/f2344580-c97c-4b89-a754-a43c9f26bc90)

Version 1.8.7
![image](https://github.com/user-attachments/assets/49073349-694d-42ca-9ae5-69bb1e0172c7)

Mods used in my test:
![image](https://github.com/user-attachments/assets/b99019f1-5527-4ba7-a8fb-e78193ae7ec2)

**Comment by CreativeMD** [comment]
Does this still happen without Blur+ installed?

**Comment by WingFrosty** [comment]
> Does this still happen without Blur+ installed?

No.

But the incompatibility was introduced in version 1.8.8. Previous versions worked fine with Blur+

**Comment by ixradioactivexi** [comment]
can confirm. blur+ and visuals are having issues.

**Comment by CreativeMD** [comment]
Can you try out this version and see if it is fixed?
https://www.dropbox.com/scl/fi/2x91t4o107iacyb64epjb/EnhancedVisuals_NEOFORGE_v1.8.10_mc1.21.1.jar?rlkey=be525j71wajs5bipuri6ccubi&st=tex9o24r&dl=1

**Comment by WingFrosty** [comment]
I can't figure out how to use that version of the mod.

The test I did before was with Fabric on Minecraft 1.21

**Comment by CreativeMD** [comment]
Oh sorry, totally forgot you are using fabric. This version should work for you:
https://www.dropbox.com/scl/fi/8iwohs39qz9n6v144n0zi/EnhancedVisuals_FABRIC_v1.8.10_mc1.21.1.jar?rlkey=ngdkggp7pr80kwdn0bw4bnjuc&st=urf10wq0&dl=1

**Comment by WingFrosty** [comment]
Tried that version and it worked! Seems to have fixed the problem.

**Comment by CreativeMD** [comment]
Very nice. I will release it for everyone soon. Thanks for the help!
