### ISSUE TITLE
Rendering issue with Vivecraft

### ISSUE THREAD

**Issue by fayer3** [CreativeMD/EnhancedVisuals#159]
with vivecraft installed, the gui renders with a solid black background

looked through the code and found this which is likely the cause
https://github.com/CreativeMD/EnhancedVisuals/commit/2cb43bec9996f8960cfa912309b0339789537963

this seems to clear the alpha channel, which vivecraft uses to render the gui in the world

not sure what exactly it is supposed to fix

![grafik](https://github.com/user-attachments/assets/609d3bf5-484d-439c-a67b-e9e3d18b68c1)

using
CreativeCore_FABRIC_v2.11.33_mc1.20.1
EnhancedVisuals_FABRIC_v1.8.1_mc1.20.1
fabric-api-0.92.2+1.20.1
vivecraft-1.20.1-1.1.11-fabric

**Comment by CreativeMD** [comment]
Problem is that I need this extra layer negate ugly render issues when blur shader is active, which causes a black shade around some of my particles. I could add an option to disable this fix, maybe it does fix the vivecraft compatibility but it will cause the issue to occur again.
Is it possible to switch to 1.21 and see if it works there?

**Comment by fayer3** [comment]
I can check, but I assume it will be the same issue

**Comment by fayer3** [comment]
exact same issue 
![grafik](https://github.com/user-attachments/assets/4c25e987-1f76-4e9b-87fc-966d9222d402)

CreativeCore_FABRIC_v2.12.9_mc1.21
EnhancedVisuals_FABRIC_v1.8.9_mc1.21
fabric-api-0.103.0+1.21.1
vivecraft-1.21-1.1.11-b5-fabric

**Comment by fayer3** [comment]
> I could add an option to disable this fix, maybe it does fix the vivecraft compatibility but it will cause the issue to occur again.

and option to disable it should be fine for vivecraft. the gui is there manually rendered, and shouldn't cause the black issues

**Comment by CreativeMD** [comment]
Added it in this version. You can disable the setting using /cmdclientconfig. Setting is called `fixBlurShader`. Can you test if it actually helps?
https://www.dropbox.com/scl/fi/acfdtstty8whnhse866h3/EnhancedVisuals_FABRIC_v1.8.11_mc1.21.1.jar?rlkey=wju370x800d1csl4btfl12ibp&st=yaspl1u2&dl=1

**Comment by fayer3** [comment]
yes that works.

**Comment by CreativeMD** [comment]
Thanks a lot for testing. New version is released which includes this setting.

**Comment by AzrannAVANA** [comment]
This issue has not been resolved for Forge & Fabric 1.20.1. I'm currently running on the 1.8.2 version of the mod and the issue appears

**Comment by CreativeMD** [comment]
@AzrannAVANA do you have enabled the setting?

**Comment by AzrannAVANA** [comment]
I didn't find the setting mentioned above- There was only the general and handler settings for the mod, and it still wasn't in the general section.. 

Is it somewhere else?

**Comment by fayer3** [comment]
afaik, that setting was not backported. even with the setting the effects would still show up on the hud though, and not the world

**Comment by CreativeMD** [comment]
Yeah, 1.20.1 is not supported anymore sorry.

**Comment by AzrannAVANA** [comment]
Ah, dang
Thanks anyhow-
