### ISSUE TITLE
Deleting all Death Message lines crashes game upon death

### ISSUE THREAD

**Issue by WesCook** [CreativeMD/EnhancedVisuals#16]
You'll need to add a check for an empty array.  Ideally a boolean config could be added to disable the feature properly as well.

Cheers.

**Comment by WesCook** [comment]
Update: Even having just one line in the config is enough to cause a crash.  It seems two or more are needed.

**Comment by CreativeMD** [comment]
Could try out this version and see if it is fixed?
https://www.dropbox.com/s/omq0kbn2p62d4dc/EnhancedVisuals%20v1.1.0%20mc1.11.2.jar?dl=1

**Comment by WesCook** [comment]
I'm actually getting a DNS error from that link.  Either momentary network problem, or the URL is invalid.

**Comment by CreativeMD** [comment]
It works fine for me ... maybe i can send it to you via discord?

**Comment by WesCook** [comment]
It's working now.  Must have been a temporary DNS problem.  Will test and get back to you.

Just to clarify, this only addresses the death messages crash, right?  It's not the rewrite you talked about earlier?

**Comment by CreativeMD** [comment]
It's the rewrite, hopefully all of your issues should be fixed.

**Comment by WesCook** [comment]
Seems to be crashing on load.  I tested across multiple Minecraft and Forge versions.

https://pastebin.com/gatQ3qr4

**Comment by CreativeMD** [comment]
Oh sorry, just redownload it. It is fixed now.

**Comment by WesCook** [comment]
New crash.

https://pastebin.com/3M27m1SA

**Comment by CreativeMD** [comment]
damn give me a sec ... just updated my windows and java doesn't want to work properly, i will try to fix it. We will be back in a few minutes.

**Comment by CreativeMD** [comment]
ok now it should work out.

**Comment by WesCook** [comment]
Heey, now it works.

It looks like a few of the effects have been toned down, which is appreciated.  For instance the water blur is nice as a subtle effect, so that players might not even notice it at first.  Otherwise it can be a bit overwhelming.

A couple bugs:

* Setting `B:noEffectsForCreative=true` leads to a crash: https://pastebin.com/74fxh5Gb
* Deleting all death messages still leads to a crash: https://pastebin.com/f3RXG7AY

A few typos in the configs:

* `"B:enalbed=true"` is included in every group.
* "factor of all other *sounsd*".
* "below or equal means the *hearbeat*"

Not sure if this is considered a bug, but dying to starvation (or while the screen is desaturated) will take a long time to restore color once you've respawned.  I'd suggest all previous visual effects should be wiped after respawning.

Personal preference, but I also think it would be best to clear effects when opening menus; especially when going back to the main menu.  Quitting while the screen is heavily blurred can make it very difficult to navigate.

Also I should probably note that I'm currently designing a 1.10 pack, so unfortunately can't use 1.11 mods.  But hopefully this testing has still been useful.

**Comment by CreativeMD** [comment]
Wow ... thank you sooo sooo much. You really helped me a lot. Short and easy to understand. I should have fixed all the stuff you have mentioned.

Unfortunately there was a bug from forge, which will prevent client side events, so EnhancedVisuals will not know when the player is hurt in 1.10.2. It is fixed for 1.11.2, so i'm really sorry, but i can't help you there.

Again thanks a lot for you help. Honestly you made my day! I will release it soon.

**Comment by WesCook** [comment]
No problem at all, glad to have helped.

Regarding the 1.10/1.11 thing, that's understandable, and I know it's a fair bit more work to maintain parity.  I should note though that I actually was intending to turn off blood splatter effects, as I was mostly interested in the water blur and hunger desaturation.  Thus the report at #17.  :)

Cheers, best of luck with the project.

**Comment by CreativeMD** [comment]
Ok, ported it back just for you, but i have no idea if it works :D

https://www.dropbox.com/s/ymnuvp72tbqaw4p/EnhancedVisuals%20v1.1.0%20mc1.10.2.jar?dl=1

**Comment by WesCook** [comment]
>Ok, ported it back just for you, but i have no idea if it works :D

Much obliged!  Though I'm afraid to say that, unfortunately, it does not.

https://pastebin.com/qLCj1S3m

**Comment by CreativeMD** [comment]
oh damn it, i forgot to delete the old classes, now it should work :D or at least not crash during startup. The only issue is that you it is incompatible with CreativeCore, unless you use this special version (just in case you are using CreativeCoreas well):
https://www.dropbox.com/s/3qf0vrbs22srzmb/CreativeCore%20v1.6.26%20mc1.10.2.jar?dl=1

**Comment by WesCook** [comment]
No CreativeCore here, so that's not a concern.  Thanks though!

I just did some testing with the 1.10 version.  It's running now, and it looks like if I disable some modules I can get just the effects I was after.  So that should work great.

I did want to raise some notes, just in case you weren't aware of them (or if they affect the 1.11 version too).

The biggest issue was the sand effect, which outright crashes right now when walking on sand.  That needs to be disabled in the configs to prevent this.

From what I could tell, four modules didn't work: enderman, fire, explosions, and potion effects.  Although I'm not actually sure what the potion effect is, so I might have missed that one.

This one isn't a bug, but just an oddity.  The water splash minimum and maximum seem to be reversed.

```
splashMaxIntensity=5
splashMinIntensity=10
```

Also I just wanted to verify, would you allow me to include this mod in a modpack?  I know some devs are iffy on allowing distribution of test builds.

Thanks!

**Comment by CreativeMD** [comment]
I don't plan to release this version (especially because it's broken), but you can of course use it in your modpack. If there are any effects you want to have, but which do not work, just contact me again and i will fix it for. Again thanks a lot for all your help!!!!

**Comment by VirtualGaming1** [comment]
@CreativeMD hay if you are looking for server testing let me know i have a private server that i have that im working on my modpack that have a few of your mods. Let me know.

**Comment by CreativeMD** [comment]
No need for that, but thank you anyway.

**Comment by VirtualGaming1** [comment]
Your welcome and let me know and is the rewrite will be on 1.10.2 also?

**Comment by CreativeMD** [comment]
Nope, sorry. Most of the effect would not work anyway, since the buy has been fixed for 1.11.2 only.
