### ISSUE TITLE
Issue with inventory using EnchancedVisuals 1.8.9

### ISSUE THREAD

**Issue by Rezonoxo** [CreativeMD/EnhancedVisuals#161]
https://github.com/user-attachments/assets/263d9bb7-135b-40e9-abb1-9445ac69e93e

Just look at the video. While hovering any slot or skin miniature - rendering in back is broken
( Without EnchancedVisuals there is no problem ) 
My mod list if needed: https://imgur.com/a/z5aHKi2

**Comment by CreativeMD** [comment]
Can you try out the newest version and see if the issue still persists?

**Comment by Rezonoxo** [comment]
I changed to version 1.8.12 and the problem no longer appears. Thanks and sorry for 3 week response

**Comment by CreativeMD** [comment]
Very good to hear!
