### ISSUE TITLE
Death message limit is set at 24

### ISSUE THREAD

**Issue by Vesperian9833** [CreativeMD/EnhancedVisuals#162]
I was trying to add a lot of custom death messages, but whenever I add more than 24 of them the config file for it resets.
Using v1.8.1 of the mod on 1.20.1 Forge.
I do know that the mod doesn't get updates for 1.20.1 or Forge anymore, but I can't use anything other than 1.20.1/Forge with the modpack that I am putting together, so I don't know what else to do besides submitting this.

**Comment by CreativeMD** [comment]
I could not reproduce this issue. Using the newest version of CreativeCore and EnhancedVisuals I can could save and load 28+ death messages. How many did you try to add? Maybe it breaks on a specific string?

**Comment by Vesperian9833** [comment]
Alright, I did a second test on the config and it somehow didn't break, managed to get up to 100
I'll be closing the issue myself, likely won't have to reopen it
