### ISSUE TITLE
 If you are on Forge 1.12.2, you will get blood when you are hit by a zombie, and then when you go to the Minecraft main menu, the blood will still be there and disappear.

### ISSUE THREAD

**Issue by Wiwoowkw123** [CreativeMD/EnhancedVisuals#163]
In Forge 1.12.2, the priority for rendering the overlay is set to the highest, so when you take damage from a zombie, you get blood, and when you go to the Minecraft main screen, the blood is still there. What should I do?
![m5hcnl4](https://github.com/user-attachments/assets/2814411c-e4b7-429f-b21e-99d28b046532)

**Comment by CreativeMD** [comment]
Actually I kept it in there because I really like this effect. I don't think there is way to disable it. They should slowly fade away. Otherwise you can respond the game or wait go ingame and jump in water, which will make the effects go away.

**Comment by Wiwoowkw123** [comment]
By the way, I like it in-game, but why does the old version of Enhanced visuals affect the main screen as well? (This issue is now fixed)
