### ISSUE TITLE
Mark 1.8.12 as 1.21 compatible

### ISSUE THREAD

**Issue by Proxi2** [CreativeMD/EnhancedVisuals#164]
Version 1.8.12 is marked as 1.21.1 compatible only. I use 1.21 and I have to manually download 1.8.12 into my mods folder. Every time I update my mods on Modrinth, it downgrades to 1.8.9 and I have to manually install 1.8.12 again. Any chance you could mark 1.8.12 as 1.21 as well? It works perfectly fine and fixes the blur+ mod incompatibility I have with 1.8.9.

**Comment by CreativeMD** [comment]
Please us 1.21.1. There is no reason to stick to 1.21. They are fully compatible with each other anyway.

**Comment by Proxi2** [comment]
I apologize for the late response. Github didn't give me a notification. I cannot update to 1.21.1. There are several mods in my mods list that haven't updated their files to mark compatibility with 1.21.1, including major mods like Nyf's Spiders and Cave Dust. I would have to manually add fabric overrides for each and every mod. As opposed to EnhancedVisuals, which is specifically marked as compatible with 1.21 and up in the mod file. It just isn't specified like that on the mod pages, so I can't update it without manually downloading the newer file.
![image](https://github.com/user-attachments/assets/a9047d4d-d2f0-4f17-b59f-d387f7899ff4)

**Comment by CreativeMD** [comment]
Sorry, but I won't. These uploads are automated I would have to go through all files and tweak this manually. I'm pretty sure this mods will fix this issue soonish (at least once the release a new version).
