### ISSUE TITLE
Desaturation effect missing (1.21.1)

### ISSUE THREAD

**Issue by AsgerJon** [CreativeMD/EnhancedVisuals#165]
I recorded a video of the problem. (My mic occasionally clicks or something, any advice on how to fix will be appreciated):
https://www.youtube.com/watch?v=B5a2Xuwkip4

When losing hunger below 3 bars, where sprint is no longer possible, the desaturation effect expected from EnhancedVisuals does not appear. 

Minecraft 1.21.1
Fabric Loader 0.16.5
Fabrick API 0.105.0+1.21.1
CreativeCore 2.12.16
EnhancedVisuals 1.8.12

System:
OS: Arch Linux x86_64
Host: ASUS MB
Kernel: Linux 6.11.2-zen1-1-zen
Display (DELL U2412M): 1920x1200 @ 60 Hz in 24*
Display (DELL U2412M): 1920x1200 @ 60 Hz in 24]
Display (DELL U2412M): 1920x1200 @ 60 Hz in 24]
DE: KDE Plasma 6.1.5
WM: KWin (X11)
CPU: Intel(R) Core(TM) i7-4790K (8) @ 4.00 GHz
GPU: NVIDIA GeForce GTX 960
Memory: 7.92 GiB / 31.29 GiB (25%)  # Without Minecraft running.

**Comment by CreativeMD** [comment]
Good catch! Thanks for reporting this issue! Fixed in the newest version.
