### ISSUE TITLE
Muffled sound when at far distances.

### ISSUE THREAD

**Issue by Destroyer457735** [CreativeMD/EnhancedVisuals#169]
Ive noticed that sound (at least explosion ringing) is very hard to hear when at distances of 1000 or more blocks from spawn.
Not sure if this will be noticed anytime soon.

**Comment by CreativeMD** [comment]
I could not repeat this issue. I teleported far away and the sound is still the same as at spawn.

**Comment by Destroyer457735** [comment]
I may have conflicting mods on my installation. I'll look through those and give you a reply. (Sorry for late response was busy.)
