### ISSUE TITLE
Blood Splatter effect is not disabled by config option

### ISSUE THREAD

**Issue by WesCook** [CreativeMD/EnhancedVisuals#17]
I may be misunderstanding this one, but disabling this setting does not remove the blood splatter effects shown when taking damage.

```
# blood splatter [default: true]
B:enabled=false
```

I find the transparency setting is also ineffective.

**Comment by CreativeMD** [comment]
I'm currently rather busy with all of my other mods. Unfortunately i cannot fix all of your issues right away. I' m planning to rewrite EnhancedVisuals and take care of all your issues afterwards. Thanks for reporting and helping to improve this mod. Hopefully it will not take longer than 1-2 weeks to finish the rewrite.
