### ISSUE TITLE
Not using full feature of the mod on server. (REASON IN SIDE)

### ISSUE THREAD

**Issue by VirtualGaming1** [CreativeMD/EnhancedVisuals#18]
The mod is not using its full feature when on servers. Reason is that the server is saying that the mod is "CLIENT SIDE ONLY" and will not using extra effects on screen (Ex: Blood splatter and red flash)

**Comment by CreativeMD** [comment]
It's a bug of forge. It is fixed for the newer 1.11.2 Forge versions.

**Comment by VirtualGaming1** [comment]
oh ok thanks for letting me know.
