### ISSUE TITLE
add config for thirst

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#19]
such as minFoodLevelEffected config, for thirst. thanks. 1.11.2 (TAN)

**Comment by CreativeMD** [comment]
Does this fixes it (because theoretically it should be already there). https://www.dropbox.com/s/niu1ytss4jtb1rp/EnhancedVisuals%20v1.1.2%20mc1.11.2.jar?dl=1

**Comment by ghost** [comment]
let me try

**Comment by ghost** [comment]
![123](https://cloud.githubusercontent.com/assets/24831406/25556650/c003d21e-2d08-11e7-9ba9-95b807288f04.PNG)
it should be kidding but i think it's not :D

**Comment by CreativeMD** [comment]
Oh sorry, just redownload it. Copied the wrong files :D

**Comment by ghost** [comment]
trying

**Comment by ghost** [comment]
where is it? which config option is it? i couldn't find again

**Comment by CreativeMD** [comment]
There is a typo just redownload it again :D

**Comment by ghost** [comment]
xD ok

**Comment by ghost** [comment]
still no config for thirst....

**Comment by CreativeMD** [comment]
It works fine for me. Don't forget to install ToughAsNails as well, otherwise the config will not be there.

**Comment by ghost** [comment]
aaaah sorry, ok.

**Comment by ghost** [comment]
hey ah, it says     I:minFoodLevelEffected=2 in thirst handler, but isn't it for hunger?

**Comment by CreativeMD** [comment]
Ups yes, fixed it (just redownload)

**Comment by ghost** [comment]
thanks...
