### ISSUE TITLE
Black Screen?

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#2]
Fast Render: OFF and still black screen... Why?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/107754454436740/193489177098697)

**Comment by CreativeMD** [comment]
That is weird, it works for me if Fast Render is turned off ... i don't what to do about it, maybe send me your Optfine configs?

**Request for a new effect**
I will this effect in the next version, but i you will have to enable it in the configs, but i'm sure it will annoy some people.

**Request for an effect change**
Sorry, but i don't feel able to draw a texture like this :(

EDIT
Sorry, i didn't want to edit your post.

**Comment by ghost** [comment]
welp photoshop can be a little help use your imagination and use photoshop along with other drawing software and the bug is fixed for me now and thanks for adding the flash! that would be more cool!

**Comment by CreativeMD** [comment]
I'm aware of Photoshop, but i doubt that i'm skilled enough to draw a proper texture for this, if you feel able to do that i'm always open for help :D
