### ISSUE TITLE
Heat overlay issue

### ISSUE THREAD

**Issue by CreativeMD** [CreativeMD/EnhancedVisuals#20]
https://github.com/tterrag1098/Blur/issues/6

**Comment by CreativeMD** [comment]
@kenijey are you sure about your heat level?

**Comment by ghost** [comment]
yeah.

**Comment by CreativeMD** [comment]
Tested it and everything works fine for me. I highly recommend to change the alphaFactor of the heat overlay effect if you think it is too much.
