### ISSUE TITLE
Important Need

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#21]
add config to disable effects in spectator mod (gamemode:3) or disable them by default without config
using MC 1.12

**Comment by CreativeMD** [comment]
Sorry, but it could take another few days, until i will find the time to fix it (also the heat overlay issue).

**Comment by ghost** [comment]
lol. ok. i will wait for you.

**Comment by CreativeMD** [comment]
Nevermind, i fixed it for you. The new version should be available for 1.11.2 and 1.12 soon. Thanks for reporting this issue.

**Comment by ghost** [comment]
oh, thank you! i was almost start crying.

**Comment by CreativeMD** [comment]
:P i'm glad i could help you out.
