### ISSUE TITLE
Weird effect sometimes that makes everything unreadable

### ISSUE THREAD

**Issue by Thyriel** [CreativeMD/EnhancedVisuals#22]
See Screenshot: https://imgur.com/a/moAj7

I'm not even sure what effect this is as i didn't got any damage or anything like that.
And it does not go away on relog / restart only removing the mod helps.

Config file: (pretty much standard, i only deactivated TaN effects as TaN temperature is disabled and lowered the heart-beat effect so it's not becoming unplayable at <4 hearts
https://pastebin.com/F2SNbEkG

**Comment by CreativeMD** [comment]
That's an effect if you are thirsty (also an additional effect for TAN). You can disable it as well if you want. It works rather similar to the black and white effect of hunger. Once you have equal or below 3 of hunger/thirst the effect will start to appear.
