### ISSUE TITLE
Captablity with First aid mod.

### ISSUE THREAD

**Issue by VirtualGaming1** [CreativeMD/EnhancedVisuals#23]
Hay so I want to see if you are able to make this work right with the first aid mod. First aid mod change the health system so the new system is going by body parts. This will be a great combine with First aid mod and this. Just want to give you a heads up for this is that the first aid mod a config that you can change each body parts. 
By default:
H
Head: 4 (2 harts)
Arms: 4
Lags:4
Foot:4
Body(chest):6

If head or Body reach 0; the player dies.
I post this is because I have this and first aid in my modpack for 1.12.2 (Real Life Modpack) and I am willing to test it out (and my testers[friends]) and let you know.

Let me know what you think. I think your mod could get even better with this since there is more way to to make Visual better.

**Comment by CreativeMD** [comment]
Could you give me some suggestions, since i haven't played with this mod yet? So it's kinda difficult for me to come up with something.

**Comment by VirtualGaming1** [comment]
One thing that i thought of is when the head health is low the vision gets bury that what i could think of so far

**Comment by VirtualGaming1** [comment]
with the latest update for First aid that i have an other mod called player revive and that the hart beet gose but will not stop with full bodypart (should be full average health) so i believe that average health have its own value data

**Comment by VirtualGaming1** [comment]
First Aid Modder made an API for his mod

**Comment by CreativeMD** [comment]
Unfortunately i have too many other things to do at the moment. So i will close it, because i doubt i will implement something like this any time soon, sorry :(
