### ISSUE TITLE
server side vs client

### ISSUE THREAD

**Issue by DoomSquirter** [CreativeMD/EnhancedVisuals#26]
Is this mod the kind that if the server has it, all the clients must have it?  or can clients still connect if it's on the server and not the client?

**Comment by CreativeMD** [comment]
The current version is client side only. Meaning you cannot install it on server side. However recently someone asked me if i could make it universal. So if it's installed on the server every client requires it as well. Furthermore he wanted synchronized configuration.

I have no released this new version, but i'm planning to do it soon. Just let me know if this is what you have in mind.

**Comment by DoomSquirter** [comment]
I was more worried about the opposite actually but it was just a question, not any suggestions or critique or anything of that nature tho.  :)  

for instance, I'm playing lost souls and the configured explosion sound with the tinnitus ringing in your ear bit was way too much for me.  I have tinnitus IRL and hearing that sound caused me to start hearing my ringing in my ear since your brain starts to ignore it passively.  lol  gotta say that sound is SPOT ON to what you really do hear.  give you credit for that.

but I was thinking for future packs that include it and if I'm on a server, if I'll be able to either not include the mod and if I did, get rejected or as what you are implying, having configurations sync'd which, to me would be a serious issue, but that's just me.  

I've always separated visuals and sound related things to client side in my mind, and just assumed they would always be like that.  but you're not treading new ground.  iirc, hc darkness did same.  must be enabled client/server, no avoidance of it, etc.  

maybe a nice in between would be certain config settings be exempt from the server sync.  that would give some ppl the option to opt out of say the tinnitus sound for example.  just a suggestion I guess.

**Comment by CreativeMD** [comment]
Yes indeed. That's why I'm not sure what to do with. I haven't uploaded the newest version yet, because of this reason. I will think of a good way to keep it configurable from the client side.
