### ISSUE TITLE
Inappropriate blood splatter with jetpack

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#27]
I'm playing Lost Souls, and when I land with my jetpack my screen gets covered in the blood effect. Sometimes so much blood I can't see anything, but I'm not actually being damaged.

**Comment by CreativeMD** [comment]
I will work on a new version, which (when installed on the server as well) will fixes all those issues.

**Comment by ghost** [comment]
Thank you. If I could make a suggestion, and I'll start a new issue if you want, base the splatter/ringing/etc. on the actual damage taken a a percent of the whole. With some mods, you end up with 40 hearts and take one heart from a ghast. The whole explosion experience doesn't make a lot of sense then. It would likely also curb the jetpack splatter since the player is taking 0% damage.

**Comment by CreativeMD** [comment]
Keep your suggestion in mind and tell it to me once i have written this new version.

**Comment by DarianLStephens** [comment]
I'm guessing the new version will be for 1.10+ or something...? Are you dropping 1.7.10 support for this mod as well?
If you are, then I would love at least a fix for blur never fully going away before you completely abandon it.
That's the one thing that's kept me from ever keeping the mod in a modpack. The blur stays forever after you get some, and makes you strain your eyes trying to see through it.
There also appears to be a weird error with Endermen, where the static is periodically swapped for the underwater overlay? It switched back and forth every second or so.

**Comment by CreativeMD** [comment]
I have dropped support for 1.7.10 almost two years ago now. Unfortunately this is not the only issue EnhancedVisuals has, therefore I can't recommend it for 1.7.10 anyway. I'm sorry to disappoint you, but I can't do everything.

**Comment by DarianLStephens** [comment]
At the very least, making the config option to disable blur actually function would be a step in the right direction.

**Comment by CreativeMD** [comment]
Sorry, but as I said I don't support 1.7.10 anymore. I won't fix this version as I have abandoned it already a long time ago.

**Comment by DarianLStephens** [comment]
Well, the 1.7.10 source is still available... maybe it's finally time I learned how to compile mods.

**Comment by CreativeMD** [comment]
Maybe this helps you: https://www.youtube.com/watch?v=7Ahshi_QjM4
Feel free to ask me about anything!

**Comment by CreativeMD** [comment]
Finally it's done the new version is available!
