### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by Neglevin** [CreativeMD/EnhancedVisuals#29]
I got this crash when I was loading my world: https://paste.dimdev.org/rijefagiku.mccrash  This world was a backup from a previous world. Any Help would be appreciated!

**Comment by CreativeMD** [comment]
Looks like a projectile hit a player without someone shooting the projectile. So it might have been a dispenser? Can you try to reproduce it? I'm currently not at home.

**Comment by CreativeMD** [comment]
I uploaded a fix for it, should be available soon.
