### ISSUE TITLE
bug: mod not working fully in servers

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#3]
i tried to fix something and its not working in servers and never doing any effects no matter what
please fix it!

REQUEST FOR A NEW EFFECT (THIS IS GOING TO BE EASY, NOT!): the fire overlay: try bending the fire texture and make the fire appear around the screen along with blood overlay but make sure fire does not obstruct the screen way too much or try creating your own animated fire texture and do the same to it

the shake: the closer you get to the explosion the more screen will shake make it like very slightly smooth shake along with a violent one based on how close you get and if you take heavy damage like: get thrown by iron golem, run over by ender dragon, blown up, something very windy and heavy flying through like the dragon, damage from falling any height! the higher the more violent shaking will be as you also shake when falling and impacting on the ground, the more damage you take like a zombie hits you in hard: you take alot of damage and the screen will shake the red screen flash with overlays when taking damage has to be more dense and bigger the more damage you take from someone.

I HOPE THIS WONT BE TOO MUCH WORK FOR YA TAKE IT EASY AND YOU MAY DO IT WITH PATIENCE!
also this mod is going to be epic with my ideas and all those features! i am trying to make my game as realistic as i can, thank you. and good luck!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/107754454436740/195831063498554)

**Comment by CreativeMD** [comment]
Forge has to be installed on the server otherwise most of the effects won't work.

I have added your request to my todo list, but for now i have to take care of my other mods. Eventually i will get to your ideas and maybe implement them (not sure). Feel free to program this features on your own and make a pull request (i can always help you out a bit).

**Comment by ghost** [comment]
thank you man to do list is good and kept for later use!
