### ISSUE TITLE
Incompatible with Improvable Skills 3

### ISSUE THREAD

**Issue by SeanChengN** [CreativeMD/EnhancedVisuals#30]
The cold/hot screen will cover the skill page (from ToughAsNails).
Here is the issue that I submit to ToughAsNails: https://github.com/Glitchfiend/ToughAsNails/issues/583#issue-372175677 (You can check the screenshots)

Mod Version: 1.2.0
Forge: 1.12.2-forge1.12.2-14.23.5.2768
Improvable Skills: 3.5.5r https://minecraft.curseforge.com/projects/improvable-skills/files

Thanks.

**Comment by CreativeMD** [comment]
Will be fixed in v1.2.1, which should be available soon.
