### ISSUE TITLE
Ticking

### ISSUE THREAD

**Issue by shoverno2** [CreativeMD/EnhancedVisuals#33]
Any hostle mob with attack equals to 0 become ticking and crash the world.
Best vanilla example is little slime.

**Comment by CreativeMD** [comment]
I don't get what you mean? Become ticking? If there is a crash can you send me the crash-report?

**Comment by shoverno2** [comment]
https://paste.dimdev.org/kifuvikipi.mccrash
It's like mini slime deal 0 damage rapidly without any cooldown. And there's no cooldown couse of there no damage. But attack is completed. And then it's calling "ticking entity" and crash the game.

**Comment by shoverno2** [comment]
https://paste.dimdev.org/kifuvikipi.mccrash

**Comment by CreativeMD** [comment]
But that's not an issue of EnhancedVisuals, Maybe it's SpecialMobs (no idea though, it's the only mod in the logs). Can't help you there sorry :(
