### ISSUE TITLE
Heartbeat Effect At Main Menu

### ISSUE THREAD

**Issue by DonTheBreton** [CreativeMD/EnhancedVisuals#34]
When killed in hardcore mode, the heartbeat effect carries to the main menu and never stops. The only way to make it go away is close and reopen the game, navigate back into the map and spectate, or start a new world. v.1.2.7-mc1.12.2.

**Comment by CreativeMD** [comment]
I'm currently working on a rewrite. Not sure when it will be released, but this bug will hopefully be fixed by then.

**Comment by CreativeMD** [comment]
This should be fixed in v1.4.0, if not open a new issue.
