### ISSUE TITLE
Screen goes black upon entering water (1.12.2)

### ISSUE THREAD

**Issue by k4rtoshkin** [CreativeMD/EnhancedVisuals#35]
This issue appeared recently, seems like instead of getting the blur effect when diving I get fully black screen for couple seconds. Any ideas?  
Mod list: 
![image](https://user-images.githubusercontent.com/58134202/69492926-0be86000-0eb1-11ea-8aaa-5bd86b5ef2fb.png)

**Comment by CreativeMD** [comment]
In order to use EnhancedVisuals alongside Optifine, Fast Render, Anisotropic Filtering and Antialiasing has to be turned off. Otherwise your screen will turn black when certain effects are active.
