### ISSUE TITLE
Damage handler and splash handler

### ISSUE THREAD

**Issue by firyy** [CreativeMD/EnhancedVisuals#36]
Hello, here's the following:

The mob damage handler only works for skeletons. I have other mobs in my modpack, but for the vanilla ones, only the skeleton hits show blood on screen. Also, fire damage only works for lava. What am I doing wrong? 

In the splash handler everythings works fine, but is it possible to add a configuration so I only get the effect when ENTERING water and not when LEAVING water? Or a way to tune the entering and leaving effects separately?

Cheers!

**Comment by CreativeMD** [comment]
I'm currently working on a rewrite for the mod which fixes the damage handler (by sending the information from the server to the client). Don't know when I finish it though. Let's hope it's not too far away.

I will post new information [here](https://github.com/CreativeMD/EnhancedVisuals/issues/27).
