### ISSUE TITLE
Half heart

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [CreativeMD/EnhancedVisuals#4]
Hello,

pardon to use the issue tracker, How do I disable the blinking/blur flashing of everything that makes the inventory unusable without disabling other effects? Also, a friend of mine with epilepsy got a terrible headache the first time he got that and we where afraid he would get an attack with the "blinking" effect on very low health. I would like to have all the effects except the one where everything is blinking and blurring and the inventory become unusable.

Thank you for your time.

**Comment by Ganjalf-Amsterdoom** [comment]
I forgot to mention i lowered I:heartLevel= to 1

**Comment by CreativeMD** [comment]
You can either disable all blur effects (by setting enabled to false) or you can set heartBeatIntensity to 0. Also you can disable the lowhealth effect which will disable the blinking overlay.

Hope this solves your question, this mod wasn't designed with epilepsy in mind :D but i hope it will be better if you disable those things. Have a great day.

**Comment by Ganjalf-Amsterdoom** [comment]
Yes, thank you for your time.
