### ISSUE TITLE
Red flash of blood 

### ISSUE THREAD

**Issue by mcb1013** [CreativeMD/EnhancedVisuals#40]
Hey thank you for the fast reply! I've disabled all of those things and more, I disabled the blood splat min max time, drown min max, drown splashes set to 0, red overlay false, red overlay intensity set to 0, min max hit effect 0. Idk if these are blood related but they sounded like it so i disabled them. Anyways I disabled everything you said and more and it still splashes red every tick or every other tick while drowning...

**Comment by CreativeMD** [comment]
This effect is disabled by default, but it looks like it's enabled in your case. Just set hitEffect in damage-handler to false. Not entirely sure if that's it, otherwise just send me a screenshot of the effect.

**Comment by CreativeMD** [comment]
I will close this issue for now, Just reopen this issue if it still persists.
