### ISSUE TITLE
phase setup error

### ISSUE THREAD

**Issue by astra-midnight** [CreativeMD/EnhancedVisuals#41]
[latest.log](https://github.com/CreativeMD/EnhancedVisuals/files/4207786/latest.log)
Game crashes at launch. I have no idea what's going on.

**Comment by CreativeMD** [comment]
The newest version should fix it. Hope everything is fine now if not just reopen this issue.

**Comment by astra-midnight** [comment]
[crash-2020-02-16_00.41.06-client.txt](https://github.com/CreativeMD/EnhancedVisuals/files/4208525/crash-2020-02-16_00.41.06-client.txt)
Fixed the phase setup error but there's a new crash now.

**Comment by astra-midnight** [comment]
Thanks for looking into this by the way. I love the mod and used it on 1.12 before 1.14. I tried but I  don't think I have permission to re-open the issue?

**Comment by CreativeMD** [comment]
Oh sorry, reuploaded the version. Just download it again. I thought you could reopen it, I will check the permissions.

**Comment by astra-midnight** [comment]
[latest.log](https://github.com/CreativeMD/EnhancedVisuals/files/4208551/latest.log)
Different error this time.

**Comment by CreativeMD** [comment]
Sorry again. The problem is that the forge installation does not allow any third party programs, which is very annoying for me. So testing is not that easy as it used to be.
The newest version will definitely work, finally got around to test it myself. Very sorry for the inconvenience.
