### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DarkScorn** [CreativeMD/EnhancedVisuals#42]
just loaded the mod, didn't even tried to join a world.

[crash-2020-03-13_12.01.22-client.txt](https://github.com/CreativeMD/EnhancedVisuals/files/4329120/crash-2020-03-13_12.01.22-client.txt)

**Comment by CreativeMD** [comment]
You have to install CreativeCore as well. Also make sure to use the newest version of it.
