### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by thomaxus** [CreativeMD/EnhancedVisuals#43]
The game always crashes when I shoot the end crystal.
[https://gist.github.com/thomaxus/3c1e5f33dbdfcafe28c8ab65500a932d](url)

After removing the mod the probem disappeared.

**Comment by CreativeMD** [comment]
Are you using the newest? Because this issue should be fixed in 1.3.4.

**Comment by thomaxus** [comment]
Yes, it's the newest. The filename is 1.3.4, it was downloaded directly from the curse newest version

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. If not please open a new issue. Thanks for your help!
