### ISSUE TITLE
TAN has been abandoned - compatibility with more modern temperature/thirst mods might be a good idea

### ISSUE THREAD

**Issue by floral-qua-floral** [CreativeMD/EnhancedVisuals#44]
I do not know if you're aware, but [Tough as Nails](https://www.curseforge.com/minecraft/mc-mods/tough-as-nails) has been abandoned for quite some time now. I think it might be a good idea to apply EnhancedVisuals's TAN features (the heat/freezing overlay & thirst blurring) to other mods that add those mechanics - the two mods that seem to still be active that fill this niche are [Matthew's Difficulty Mod](https://www.curseforge.com/minecraft/mc-mods/matthews-difficulty-mod) and [SimpleDifficulty](https://www.curseforge.com/minecraft/mc-mods/simpledifficulty). MDM doesn't seem to be open-source, though.

It'd be nice to get to make the switch to more modern mods without having to give up the special temperature and thirst based overlays from EV. They make temperature management a lot easier to keep track of by making dangerous temperatures affect the whole screen instead of a single UI element, and the thirst blurring adds a very intense feeling of urgency when dehydrated. I'd love to be able to move away from relying on an abandoned mod, while keeping these features.

**Comment by CreativeMD** [comment]
I won't add any new features for 1.12. All I will do is fix bugs and maybe add more cross mod combat (like events for other mods to use). Tough as Nails is not available for newer version, which means I will support different mods in 1.14+, but not for 1.12. People will stick to Tough as Nails in 1.12 anyway.
