### ISSUE TITLE
NullPointerException in SlenderHandler

### ISSUE THREAD

**Issue by Chumbanotz** [CreativeMD/EnhancedVisuals#47]
Hello, I see you've added support for the Mutant Enderman. A user of my mod showed me a crash log claiming it was caused when mutant endermen spawned. Here is the line the issue is on:
https://github.com/CreativeMD/EnhancedVisuals/blob/076f05e1afba0c564d929c7db438a65fe914e6db/src/main/java/team/creative/enhancedvisuals/common/handler/SlenderHandler.java#L68
Null is passed where there should be an EntityPredicate, which I noticed is passed for normal enderman from your SelectEndermanEvent.

**Comment by CreativeMD** [comment]
Oh thanks for reporting this issue. The predicate cannot be null apparently. Released a new version which should fix it.
