### ISSUE TITLE
I cant play Minecraft 1.12.2 forge 14.23.5.2776 With enchanced visuals And it failes to start at the 3rd mod loading proccess

### ISSUE THREAD

**Issue by MineShafter1** [CreativeMD/EnhancedVisuals#48]

**Comment by CreativeMD** [comment]
Make sure to install CreativeCore and update Forge to the latest version.

**Comment by MineShafter1** [comment]
> Make sure to install CreativeCore and update Forge to the latest version.

Thank you <3
