### ISSUE TITLE
Ice overlay not going away till restart 1.7.10

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#49]
Would it still be possible to get support for that? Maybe it's just a quick fix. Else I'll try to dig myself

**Comment by CreativeMD** [comment]
I don't support 1.7.10 anymore. Sorry, but you will have to fix it yourself. I can also help you there.

**Comment by ghost** [comment]
Ok, thanks. If I need help, where should I ask? On issues?

**Comment by CreativeMD** [comment]
Rather do it on discord.
