### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by Djjunior95Real** [CreativeMD/EnhancedVisuals#52]
There is a bug with the enderman. normally the screen would be filled with static, but if you get really close the static dissapers and turns into a white layer. and this gets really annoying when you start getting blood on your screen, because they turn into transparent red squares. this is going on in the minecraft 1.15.2

**Comment by CreativeMD** [comment]
Is this still a thing in 1.16.2?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still occurs in 1.16.3 just let me know.
