### ISSUE TITLE
[suggestion] add Napalm Creeper from Epic Siege Mod

### ISSUE THREAD

**Issue by Seth0067** [CreativeMD/EnhancedVisuals#53]
Since ESM is likely no more past 1.12, it would be great to see their napalm creeper option turn up in this mod. It fits within the umbrella of Enhanced Visuals and is a great combo with the blast deafening audio effects. PTSD a guarantee!

**Comment by CreativeMD** [comment]
Not for 1.12, sorry. If the mod updates contact me again.

**Comment by Seth0067** [comment]
@CreativeMD - what i meant is that Enhanced Visuals should pull this feature in for 1.16 since you guys are updating and they are not.

**Comment by CreativeMD** [comment]
I don't want to use stuff from other mods, unless i have the permission to do so.
