### ISSUE TITLE
I can't use this mod on my server (server won't start/won't join)

### ISSUE THREAD

**Issue by SpencerMeow** [CreativeMD/EnhancedVisuals#54]
I'm on Forge 1.14.4. So I obviously assume this is a client side mod, so I only put it on client only, and when I try to join my server it says "mismatched mods list" which is weird since I have everything perfectly matched but clientside mods, so I go to the log 
[latest.log](https://github.com/CreativeMD/EnhancedVisuals/files/5362310/latest.log) and see that Enhanced Visuals  "rejected their server side version number" and since there was no other version in the server at all, I copied the one from client over to the server too. But when I try to do that, the server crashes trying to start 
[crash-2020-10-11_17.59.00-server.txt](https://github.com/CreativeMD/EnhancedVisuals/files/5362312/crash-2020-10-11_17.59.00-server.txt)

do you know if there's just something dumb I'm doing wrong or if you could procure a fixed version (preferably 1.14.4)

**Comment by SpencerMeow** [comment]
I also saw you fixed crashing on dedicated servers on 1.5.3 but it's only on 1.15.2

**Comment by CreativeMD** [comment]
Sorry, but I don't support 1.14 anymore. The versions for 1.16.2 are the first working ones (on server and client). Can't help you there. You will have to remove the mod until you can update.
