### ISSUE TITLE
Visual error wtih Wailia (1.12.2)

### ISSUE THREAD

**Issue by Shibva** [CreativeMD/EnhancedVisuals#56]
Hello, I have been looking for a mod that adds realistic damage to 1.12.2 for a bit now and I was happy when I found this mod, unfotrunatly I was disapointed when this happend
![image](https://user-images.githubusercontent.com/38770780/99911268-2cfcb000-2cc1-11eb-803e-f856520ad1d4.png)
This is when I was looking at a block with Wailia rendering on 

and after I tuned it off, things whent back to normal,

after some tinkering I have found out this issue only exist if the item rendering shows up on the display for the block you are looking at
![image](https://user-images.githubusercontent.com/38770780/99911400-202c8c00-2cc2-11eb-8ae6-213b96b06d2f.png)

if you can look into this and fix it then I, along with the countless others that use Wailia would deeply appreciate this fix

(side note: texture packs are present and Optifine is present as well; Issue has been confirmed with WAILIA)

**Comment by Shibva** [comment]
![image](https://user-images.githubusercontent.com/38770780/99911449-7bf71500-2cc2-11eb-8fcd-2c0d3b243133.png)
the image here seems to be fine if your in creative and the effects are not rendering

**Comment by Shibva** [comment]
Update: this is also caused when viewing item blocks via pyrotech

![image](https://user-images.githubusercontent.com/38770780/99920225-102ba100-2cf0-11eb-8204-d7247026c290.png)
confirmingg that whenever the mod tries to render an item when the visuals with this mod that the error occurs

**Comment by Shibva** [comment]
more evidence
![image](https://user-images.githubusercontent.com/38770780/99931246-cb206280-2d21-11eb-841c-fbd1fddda5c1.png)

![image](https://user-images.githubusercontent.com/38770780/99931263-d7a4bb00-2d21-11eb-9fd3-07d76fe49ad6.png)

**Comment by CreativeMD** [comment]
I cannot reproduce this issue, works just fine for me. Can you send me your mod list?

**Comment by Shibva** [comment]
[Shibv's Calamity-1.0.0.zip](https://github.com/CreativeMD/EnhancedVisuals/files/5712081/Shibv.s.Calamity-1.0.0.zip)

This is done via Twitch modpack export (for simplicity, use the import, for doing things manually, please check all files and move them into place)

i will post a video on how to recreate this
[optionsof.txt](https://github.com/CreativeMD/EnhancedVisuals/files/5583342/optionsof.txt)
[optionsshaders.txt](https://github.com/CreativeMD/EnhancedVisuals/files/5583343/optionsshaders.txt)
[options.txt](https://github.com/CreativeMD/EnhancedVisuals/files/5583344/options.txt)

(side note: for this to work, please delete the config for WAWLA, a temporary gameplay fix has been made to allow me to play with both mods present until further notice


Additional Note: due to me being a tester for another mod and rulering it out being a potential issue, I have removed the mod for the sake of not distributing it

**Comment by Shibva** [comment]
Please note I was using a keybind to disable the display For WAILA while doing this video and keep an eye on it

I hope this helps
https://thumbs.gfycat.com/CleanFabulousBarnacle-mobile.mp4

**Comment by CreativeMD** [comment]
After a lot of testing I found out which mod caused this issue. It is ThaumicWonders. Unfortunately this mod uses some OpenGL stuff the wrong way, which caused my mod to break. I implemented a hacky fix for it in the newest version. Hope everything works fine now.

**Comment by Shibva** [comment]
![image](https://user-images.githubusercontent.com/38770780/100003654-7407a580-2d94-11eb-9851-c63a6487c370.png)

YES YOU DID IT

thanks a Thousand, this not only fixed Wonders, but other mods that might use Open GL incorrectly
