### ISSUE TITLE
Incompatablity when using Sacrifical Dagger

### ISSUE THREAD

**Issue by Shibva** [CreativeMD/EnhancedVisuals#57]
Hello Again, its me, you still have that pack of mine, well if you do I found that when you use the Sacrifical Dagger from Blood Magic with this mod present it causes a crash after a short time freezing the game

From what I have seen, it seems to be when you use it, you "hurt Yourself in some way
![ezgif-3-2df1f34461f8](https://user-images.githubusercontent.com/38770780/100188220-c42b5880-2eb7-11eb-84a9-539e277b365a.gif)
this is the action being done with a Right click with the mod disabled

Since it produced a Crash Report I will post it below, my best guess is that the mod tried to render the Hurt particles and somthing bewteen that and Blood magic did not like what it was trying todo
I hope this can help you out fix another mod that others like 

Same pack as before in #56 

[crash-2020-11-25_00.24.25-client.txt](https://github.com/CreativeMD/EnhancedVisuals/files/5594659/crash-2020-11-25_00.24.25-client.txt)

**Comment by Shibva** [comment]
Edit: Removed Wearable Backpacks and added V0id's smart backpacks

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
