### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Taknax** [CreativeMD/EnhancedVisuals#59]
If i die the first time after restart the client crashes.

https://pastebin.com/PB7hdB6M

**Comment by CreativeMD** [comment]
Are you sure this issue is caused by EnhancedVisuals, I can't find any connection to it.

**Comment by Taknax** [comment]
It was because something was messing with the zombie AI. It triggered by EV, but not caused. Ty for your reply and this beautiful mod.
