### ISSUE TITLE
[Visual Glitch] Enhanced Visual and InGame Info XML.

### ISSUE THREAD

**Issue by bontavi** [CreativeMD/EnhancedVisuals#6]
Minecraft - 1.10.2
Forge - 12.18.3.2221
Enhanced Visuals - 1.0.8
InGame Info XML - 2.8.1.89-universal .
Client log - http://pastebin.com/DfGLPrhW

Hello, i have found some Visual Glitch (bug ) and i dont know, which mod is causing this. But, if you have both mods in one pack and if you try to pick item/tool with nbt tag. Your visual goes very glitchy - http://imgur.com/a/NOMpP . In these screenshots, you can't see, but visual becomes like rainbow colored . I have tried to reset both mods, configs and it still happen. In game Client logs, i have found - 

[02:55:25] [Client thread/ERROR]: ########## GL ERROR ##########
[02:55:25] [Client thread/ERROR]: @ Post render
[02:55:25] [Client thread/ERROR]: 1284: Stack underflow .

**Comment by CreativeMD** [comment]
I think it's fixed in v1.0.9 could you test it for me?

**Comment by bontavi** [comment]
A moment.

**Comment by bontavi** [comment]
Yes, it got fixed. Thank you :)

**Comment by CreativeMD** [comment]
Nice, thanks for testing and reporting this issue.
