### ISSUE TITLE
Custom Death Messages 

### ISSUE THREAD

**Issue by Shibva** [CreativeMD/EnhancedVisuals#60]
Its me again, I was trying to add my Own Death messages but for some reason the mod keep on resetting the config, I kind of find in inconvinet for I was trying to add one such as
"You need to Try Harder at living"
"Press F to pay respects"

can you please fix this so I can use my own custom death messages (I tried doing this multiple ways and to ensure that the format was correct

**Comment by CreativeMD** [comment]
Which version of the mod are you using? If you are using 1.12, just configure it via the ingame settings. If you are using 1.16 the setting can be found inside enhancedvisuals-client.json. Would also be helpful if you could send me your file so I could test it myself.

**Comment by Shibva** [comment]
I dont see the config opon for that in the games config

this is 1.12.2, same modpack as before

**Comment by CreativeMD** [comment]
I would highly recommend to configure it via the mod settings. Also make sure your version is up-to-date. I will close this issue for now. If it still doesn't work (despite having the newest version), just let me know.

**Comment by Shibva** [comment]
I may be going crazy here, but I cant find it in the config options in game

is it in handlers or in general?
and what would be the path to find it?

**Comment by Shibva** [comment]
It reset this,  
and I cant find the config for it in game

and this is the updated version

**Comment by CreativeMD** [comment]
Oh right, damn I'm sorry. It's actually not a client side option. You can configure it ingame using the command /cmdconfig -> EnhancedVisuals -> Death Messages. Or in the config file "enhancedvisuals.json".

**Comment by Shibva** [comment]
I tiried that and made an edit
it just undid it

**Comment by Shibva** [comment]
![image](https://user-images.githubusercontent.com/38770780/101831340-c5899180-3b03-11eb-8d18-748b94676943.png)

I tried wiht this, Does this look correct

if so then why does it keep resetting it?

**Comment by Shibva** [comment]
Oh, I see now, Thanks for the guide

Might be best to have it as a config option or acessed via the config menu, make things a bit easier

**Comment by Shibva** [comment]
also I see why now, it only is made to add so many, could there be a way to make this where you can add more of them? because that's what's causing the issue it seems, I tried to add more but it only is meant to work with so many

**Comment by CreativeMD** [comment]
There shouldn't be a limit and unfortunately it's not a good idea to make it accessible via a menu, because it's actually server configuration.

**Comment by Shibva** [comment]
well How do I add more than the ones that are Preset?
I dont see any option to add more, like no additon button

**Comment by Shibva** [comment]
Also Since were here talking, I would also like to bring up some sort of error wiht little tiles, ill post it later in the proper github so keep an eye out for it 😉

**Comment by CreativeMD** [comment]
And another mistake. Released a new version which should fix it. Sorry for the inconvience.

**Comment by Shibva** [comment]
eh, its ok, sometimes we forget the little things

thanks and I hope the other issue (https://github.com/CreativeMD/LittleTiles/issues/533) was something I helped out a bit in to

**Comment by CreativeMD** [comment]
Yeah, I'm aware of this issue, but I can't do anything about it at the moment. I need to finish some features first then I will see what I can do.
