### ISSUE TITLE
[1.12.2] Some effects are replaced with a black screen

### ISSUE THREAD

**Issue by SpencerMeow** [CreativeMD/EnhancedVisuals#61]
I'm on the latest 1.12.2 version, and some effects like the transition in and out of water, and your heart beating on low health, make your screen go black until the effect is over instead of actually displaying what it's supposed to. The only other mods I could think of that could cause this are Dynamic Surroundings and First Person Render 2.

**Comment by CreativeMD** [comment]
In order to use EnhancedVisuals alongside Optifine, Fast Render, Anisotropic Filtering and Antialiasing has to be turned off. Otherwise your screen will turn black when certain effects are active.

**Comment by SpencerMeow** [comment]
> In order to use EnhancedVisuals alongside Optifine, Fast Render, Anisotropic Filtering and Antialiasing has to be turned off. Otherwise your screen will turn black when certain effects are active.

Ooooh thanks, I forgot I was using antistrophic filtering, which i don't usually do.
