### ISSUE TITLE
Current 1.12.2 build does not have Hunger Desaturation (1.3.22).

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#63]
version 1.3.22.

Title says it, there is no desaturation when you're hungry.

Even when using ONLY this mod and creative core, it does not work. There is no desaturation.

HOWEVER, if I use the outdated 1.2.7 jar, it _does_ work (_on the outdated version there **is** desaturation_).

Any chance for a fix?

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
