### ISSUE TITLE
"maxHealth" and "maxHealthPercentage" - how it works?

### ISSUE THREAD

**Issue by Rugowaka** [CreativeMD/EnhancedVisuals#64]
Hello
Can you explain, please, how works "maxHealth" and "maxHealthPercentage" options in config file?
I try to set them at any values, from ordinary to some crazy, again and again, but cant see any changes - heartbeat always start from 3 hearts (6hp)
Am I stupid? :(

EV 1.3.20

> _English is not my native language, sorry for mistakes_

**Comment by CreativeMD** [comment]
Make sure to look at the right config file, it's "enhancedvisuals-client.json". maxHealthPercentage is only used if useHealthPercentage is set to true.
