### ISSUE TITLE
Latest 1.12.2 Build that fixed Saturation, new bug: When loading the game, the Main Menu starts of desaturated. Over time, it gradually comes back.

### ISSUE THREAD

**Issue by ghost** [CreativeMD/EnhancedVisuals#65]
Thanks to CreativeMD for fixing the last bug, but there's a new bug now!

When loading the game, Enhanced Visuals causes the Main Menu to be 100% desaturated. If you give it a minute, it will slowly re-saturate back to normal color.

This occurs with ONLY Enhanced Visuals installed alongside Creative Core in forge 1.12.2, so I know it's not a conflict with other mods.

**Comment by CreativeMD** [comment]
Fixed in the next update. Thanks again!
