### ISSUE TITLE
Explosion sound suppression regulation

### ISSUE THREAD

**Issue by MrJakob99** [CreativeMD/EnhancedVisuals#68]
Can somebody tell me which option in the .json file I have to lower, so I can hear the explosion and not instantly getting the ringing in the ears.
So like I can hear the explosion shortly and than the tinnitus or at least I can hear the explosion to like 20% and the rest is muffled by the tinnitus.
It would be cool if somebody could help me with this :)

**Comment by CreativeMD** [comment]
If you are using the 1.12 you can change it in th mod menu in 1.16 you have to change it in the config file (enhancedvisuals-client.json).
It's in explosion-handler maxExplosionVolume.
