### ISSUE TITLE
Enhanced Visuals stays after leaving game.

### ISSUE THREAD

**Issue by bontavi** [CreativeMD/EnhancedVisuals#7]
Minecraft - 1.10.2
Forge - 12.18.3.2221
Enhanced Visuals - v1.0.8

Hello, i have found this issue during game test. After you have died and left your world in main menu, you can still see enhanced visual effects - https://gyazo.com/ea743890e0e31e0d30ac43df7fdb4f09 .

**Comment by CreativeMD** [comment]
I know, but it's actually not a glitch but a feature. The only thing i need to add is that it should slowly fade away.

**Comment by bontavi** [comment]
oh, okey. :) thanks really cool mod.

**Comment by CreativeMD** [comment]
Effects slowly fade out in main menu in v1.0.9.
