### ISSUE TITLE
[1.16.4/5] Sound muting interferes with Dynamic Surroundings volume scaling

### ISSUE THREAD

**Issue by OreCruncher** [CreativeMD/EnhancedVisuals#70]
Dynamic Surroundings uses Mixin to hook getClampedVolume().  EnhancedVisuals redirects the call to it's own private version.  As a result Dynamic Surroundings does not have a chance to apply various volume effects to a sound play.  For example, if a player adjusts the Footstep volume scaling factor it will not have any affect on the sound.

Not sure of the best way forward to resolve atm.  On the surface I am wondering if it would be possible to add a config option to disable muting, and let the regular Minecraft routine proceed.  I am not sure if it could be resolved on my end.  I will need to do some thinking.

**Comment by CreativeMD** [comment]
I reworked my hook, both mods should work fine again. If not please let me know.

**Comment by OreCruncher** [comment]
@CreativeMD Thank you!
