### ISSUE TITLE
Keep getting this crash with the new version. EnhancedVisuals_v1.3.26_mc1.16.5.jar

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [CreativeMD/EnhancedVisuals#73]
[crash-2021-04-22_16.45.15-client.txt](https://github.com/CreativeMD/EnhancedVisuals/files/6361178/crash-2021-04-22_16.45.15-client.txt)

**Comment by CreativeMD** [comment]
Just redownload the same version, it's fixed.
