### ISSUE TITLE
Client/Server hangs when dying from void damage.

### ISSUE THREAD

**Issue by CrazyContraption** [CreativeMD/EnhancedVisuals#75]
*Pre-note: because of the nature of the crash, logs denote nothing of interest, and simply display tick/lag warnings, and save no records once the freeze occurs.*

 - Using Mod version 1.3.28 for MC 1.16.5
 - Using Forge Universal 36.1.0

Tried with a full modpack and as standalone with CreativeCore as the only additional accomplice, both with the same crash persisting. 

Client/server hard freezes and never recovers when a client dies from an instant kill, such as `/kill`, and rarely from fall damage if it one-hit-kills the player.

From testing, disabling the "damage" handler in the configs prevents these issues, and allows normal gameplay to continue without hanging. Normal damage and deaths seem unaffected from extensive testing even with the handler enabled.

Client hanging was consistent on multiple machines, and servers.

Please let me know if more information is needed.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks a lot for your informative description of the issue!
