### ISSUE TITLE
EnhancedVisuals (enhancedvisuals) has Encountered an Error During the Common_Setup Event Phase

### ISSUE THREAD

**Issue by Coraline77447** [CreativeMD/EnhancedVisuals#77]
Minecraft: 1.17.1
EnhancedVisuals: 1.4.0
Forge: 37.0.22
Optifine Installed?: No, not compatible with forge 1.17 yet.
Crash Report: https://pastebin.com/mGsCn8N0
Log: [latest.log](https://github.com/CreativeMD/EnhancedVisuals/files/6924244/latest.log)

**Comment by Coraline77447** [comment]
Btw EnhancedVisuals is the 3rd mod in my personal modpack for 1.17.1 to fail/crash during mod loading today and after waiting for a little more than a week cause of forge's data pack wasn't using the correct pack formatting number...

**Comment by CreativeMD** [comment]
Forgot to release a new version of CreativeCore should be available in a few minutes.
