### ISSUE TITLE
Casting trident to potion causes crash

### ISSUE THREAD

**Issue by Angular-Angel** [CreativeMD/EnhancedVisuals#78]
The game crashes when at team.creative.enhancedvisuals.common.event.EVEvents.impact tries to cast a trident to a potion.

[crash-2021-08-06_16.41.57-server.txt](https://github.com/CreativeMD/EnhancedVisuals/files/6948194/crash-2021-08-06_16.41.57-server.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version
