### ISSUE TITLE
Enhanced Visual and Fullscreen Windowed (Borderless) incompatible

### ISSUE THREAD

**Issue by bontavi** [CreativeMD/EnhancedVisuals#8]
Minecraft - 1.10.2
Forge - 12.18.3.2221
Enhanced Visual - 1.0.8
Fullscreen Windowed (Borderless) - 1.5.0

My video settings on minecraft - https://gyazo.com/19568d7ba7706deea6e6838bb730bcbb

Hello, I found another issue. Enhanced Visual and Fullscreen Windowed ( borderless ) both mods in my modpack and encountered some issue. If you are trying to make minecraft window in fullscreen by pressing f11 it makes minecraft window to scale to big. You can see it, how it look in screenshots .

Before - https://gyazo.com/06d73cf7ac199440a73709103da87af6
After pressing f11 - https://gyazo.com/472a41971dd0d674af9a2711fcf5fffc . As you can see after pressing f11, your window and all information in mainmenu at the bottom disappears. Same can happen, when you are trying to get into fullscreen in game.

Unfortunate, there is no crash log or fml log for this one. I haven't changed any configs for both mods.

**Comment by CreativeMD** [comment]
Thanks for reporting, but you should be able to just do it again, which should work just fine (at least for me). Nonetheless i will try to find out what could possibly cause this issue and try to fix it.

**Comment by bontavi** [comment]
Hey, if you will need, there is list of mods which i'm using on modpack - http://pastebin.com/Znrdith4

**Comment by CreativeMD** [comment]
Seems to be fixed in v1.0.12
