### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by megumann** [CreativeMD/EnhancedVisuals#81]
Visual effects seem to be disabled on multiplayer servers.

**Comment by CreativeMD** [comment]
It needs to be installed on the server as well in order to work properly.

**Comment by Gabo6480** [comment]
I suppose it is because you need to receive certain events from the server or something like that. Is there a chance you could consider creating a bukkit plugin that makes this compatible for clients with this mod installed?

**Comment by CreativeMD** [comment]
Not really planned. Not sure if there is a way to send packets for a forge mod to a client.

**Comment by Gabo6480** [comment]
Simple Voice Chat and Emotecraft are already doing something similar, so I believe it is possible.

**Comment by megumann** [comment]
More Player Models also does this.

2021年12月27日(月) 8:51 Gabo6480 ***@***.***>:

**Comment by CreativeMD** [comment]
Ok, but still, I'm not really into plugin development, sorry.
