### ISSUE TITLE
Crash after a death under water

### ISSUE THREAD

**Issue by Finelarme9** [CreativeMD/EnhancedVisuals#82]
Hello. Thank you for this mod. there is a crash when the player dies under water (gamemode survival).

**Details**
"The game crashed whilst unexpected error. Error: java.lang.IllegalArgumentException: bound must be positive."
=> https://pastebin.com/raw/1qK4BMQ4

**Using**
1.18.1-forge-39.0.14
1.18.1-OptiFine_HD_U_H4
CreativeCore_v2.4.1_mc1.18.1.jar
EnhancedVisuals_v1.4.3_mc1.18.1.jar

**EDIT**:
- When I use lowhealth to disabled: true, there is no more problem.

**Comment by CreativeMD** [comment]
It's because you have configured exactly one death message. It is fixed in the newest version.
