### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by LightHallows** [CreativeMD/EnhancedVisuals#85]
Whenever I turn on shaders have a glitch on effect as on the video + on low hp effect

https://www.youtube.com/watch?v=QTqGVKEVZZ4&ab_channel=AndreyMasloff

**Comment by CreativeMD** [comment]
In order to use EnhancedVisuals alongside Optifine, Fast Render, Anisotropic Filtering and Antialiasing has to be turned off.
