### ISSUE TITLE
Crash when trying to load on server

### ISSUE THREAD

**Issue by TheButterbrotMan** [CreativeMD/EnhancedVisuals#86]
https://bytebin.lucko.me/VHp8Hqnbws

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Thanks for reporting this bug!

**Comment by TheButterbrotMan** [comment]
Ehm no, its not.

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/EoHJP0SPtJ

**Comment by CreativeMD** [comment]
Should be fixed in the newest CreativeCore version. Can you try it out?
https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3758246
