### ISSUE TITLE
Configs Saturation needs comment

### ISSUE THREAD

**Issue by Laifsyn** [CreativeMD/EnhancedVisuals#88]
`"saturation": {
      "enabled": true,
      "opacity": 1.0,
      "fadeFactor": 0.0005,
      "saturation": {
        "min": 2,
        "minValue": 0,
        "max": 8,
        "maxValue": 1
      },
      "desaturate": {
        "disabled": false,
        "opacity": 1.0
      }`
      

This snippet from the config also affects the game. In the sense that, if I lower the saturation enough, I get a gray like launcher. So it would be good if there's a comment warning about it. lest they don't know what's the culprit
(the gray do however seems to fix going into spectator when inside game though)
Fabric latest version

**Comment by CreativeMD** [comment]
I highly recommend to use the gui configuration instead. You can open it by using the command /cmdclientconfig ingame. There you can change configuration on the fly and see what it does.
