### ISSUE TITLE
Screen blacking out on death, stays. 

### ISSUE THREAD

**Issue by caligator** [CreativeMD/EnhancedVisuals#9]
Essentially what it says. when I die in game, my screen will black out when I hit respawn and doesnt change back-- even when I open menu and try to exit, the menu screen is blacked out as well as the main menu. I've been trying to figure out what might control that in the config, but I'm at the point of going into the mod and ripping out the image used for making the screen black. any help would be greatly appreciated.

**Comment by CreativeMD** [comment]
If you are using Optifine disable Fast Render

**Comment by caligator** [comment]
dont use it-- closest I have is BetterFPS. only use mods off curseforge

**Comment by CreativeMD** [comment]
Can you give me a list of all your mods, your Minecraft version, forge version?

**Comment by caligator** [comment]
Its a lot, but no other issues present from any other mod. Enhanced Visuals is the only one glitching. I dont have it listed in the mods here because thats already a given.

MC: 1.10.2
FORGE: Forge-12.18.3.2221

MODS_________________
Deadly Monsters
Chunk Edge Indicator
Abyssalcraft
Actually Additions
Advanced Rocketry
Agricraft
Animus
Aquaculture
ArsMagica 2
AutoRegLib
Autosappling
Battle Towers
Baubles
Better Builders Wands
Better FPS
Better Than Bunnies
Bibliocraft
Big Doors
Biomes o Plenty
Blood Magic
Bookshelf
Botania
Brandon's Core
Bullseye
Chameleon
Chest Transporter
Chickens
Chisel
Chisel and Bits
Chunk Animator
Clipboard
Code Chicken Lib
Colossal Chests
Common Capabilities
Compatlayer
Cooking for Blockheads
Craftable Saddles
Crafting Tweaks
Cyberware
Cyclops Core
Dark Utilities
Davinci's Vessals
DeathQuotes
Deep Resonance
Double jump
Draconic Evolution
Dragon Tweaks
Dungeon tactics
Dynamic Surroundings
ElecCore
EnderCore
EnderIO
Ender Zoo
End Metals
environmental tech
extra alchemy
extra golems
extra utilities 2
extreme reactors
fairy lights
farseek
fastleaf decay
forestry
forgelin
giacomos experience seedling
glass shards
googly eyes
grapplemod
gravestone
grimoire of Gaia 3
guide API
harvest
hatchery
helper tools
hydrophobic skeletons
immersive engineering
infernal mobs
infinity lib
integrated dynamics
integrated tunnels
inventory tweaks
iron chest
item scroller
ivtoolkit
JEFB
JEI
JEI Bees
Journeymap
jurassicraft
just enough resources
kleeslabs
librarianlib
libvulpes
llibrary
lloverlay reloaded
lunatrius core
Malisis core
malisis doors
mantle
mcjtylib
mc multipart
morebees
more chickens
morpheus
moving world
mowzies mobs
natural pledge
neat
nethercore
nether metals
ninja gear
no mob spawning on trees
simmedcow's no more recipe conflict
omlib
open computers
open modular turrets
overlord
packing tape
pam's harvestcraft
platforms
potion core
project 3
psi
quark
railcraft
random things
recurrent complex
refined storage
reliquary
reliquia
reptile mod
rftools
rftools dim
roguelike dungeons
roots
ruins
rustic
schematica
shadowMC
shetiphiancore
shin colle
simple corn
snad
sophisticated wolves
Soundfilters
spartan shields
stackie
storage drawers
streams
tails
tinkers
tinkers golems addon
tiny progressions
torchmaster
totemic
underp hangables
unidict
valkyrielib
vending block
villagebox
waddles
waila
waila harvestability
wanion lib
waystones
wolf armor
zero core

**Comment by CreativeMD** [comment]
Could you try out the newest version (v1.0.9) does this fix your issue?

**Comment by caligator** [comment]
sorry- busy week at work. the fix made it worse. when I just have any effect on screen it blacks out now.

**Comment by CreativeMD** [comment]
Is fixed in v1.1.1 for 1.11.2. No fix for 1.10.2 sorry :(

**Comment by Foxgreat** [comment]
Came up with same problem on 1.12.2, and as i see here's no suggestion to solve it so here's my detailed changelog to how i fix it.
At first i had default Optifine config and i have blackscreen problems
Then i changed fastrender:off and everything goes white, so i restarted client and it goes fine again.
After that blackscreen don't shows again
