### ISSUE TITLE
[Question]How can I localize all the deathMessages of enhancedvisual.json

### ISSUE THREAD

**Issue by Kasualix** [CreativeMD/EnhancedVisuals#95]
Version: EnhancedVisuals_v1.3.32_mc1.16.5.jar
[default config](https://pastebin.ubuntu.com/p/svYq5D5gQs/)
I tried to use localized key [here](https://pastebin.ubuntu.com/p/MdHjgmYNNS/) but it does't work.

**Comment by CreativeMD** [comment]
You can't, because they are configurable. Use the command /cmdclientconfig and change the death messages as you want to.
