### ISSUE TITLE
Bug with water blur

### ISSUE THREAD

**Issue by TheSexyYeti** [CreativeMD/EnhancedVisuals#96]
I keep having issues with the blur coming in and out of water. And I have nothing installed that would be causing it. No optifine or dynamic light mod. Black boxes coming out. And this black icon going in and coming out sometimes.
![bug](https://user-images.githubusercontent.com/50222286/189544932-56063cd8-0e36-4352-a228-145dbb3982eb.png)
![bug2](https://user-images.githubusercontent.com/50222286/189544937-5a0b4cee-107d-4ea5-ac25-cb2241b8039f.png)

**Comment by CreativeMD** [comment]
That is not a bug, but a feature called splash. You can configure it using the command /cmdclientconfig .

**Comment by akai-hana** [comment]
what about the black thing in the middle on the first screenshot?

**Comment by Aceplante** [comment]
I am also seeing a black box upon entering or exiting water, and when I'm at low health and have the "heartbeat" effect. For some reason though, I couldn't seem to get a screenshot

**Comment by CreativeMD** [comment]
@Aceplante2 If you are using Optifine you need to disable certain settings to make it work. You can check that by going to shaders. If you are using embeddium the same might happen. You can install Oculus to get around that I think.

**Comment by Aceplante** [comment]
I am not using optifine, but I am using embeddium. I am fairly certain I use oculus tho

**Comment by CreativeMD** [comment]
Are shaders enabled if yes it should definitely work. If not you need to tweak the settings a bit.

**Comment by Aceplante** [comment]
its a shader? i may have disabled them

**Comment by CreativeMD** [comment]
It is a shader, that's why it needs to be enabled.

**Comment by Aceplante** [comment]
it still happens and this is what I see when I toggle shaders:

![fweewfwef](https://github.com/CreativeMD/EnhancedVisuals/assets/101857505/856e987e-ce30-400d-802d-7c93fb5fe447)

**Comment by Aceplante** [comment]
when I get out of water, a large black box covers most of my screen

**Comment by CreativeMD** [comment]
As I said shaders not be enabled. Maybe your graphic card does not support it? You can disable the effect in the config. Use the command /cmdclientconfig. The effect is called water splash.

**Comment by Aceplante** [comment]
I disabled that but a minor version happens when I get at low health too... it seems hard to avoid?

**Comment by CreativeMD** [comment]
You can disable this effect as well handlers -> low health -> blur.
