### ISSUE TITLE
Crash report 1.19

### ISSUE THREAD

**Issue by HappyPlaysFeet** [CreativeMD/EnhancedVisuals#98]
Error: java.lang.NoClassDefFoundError: team/creative/creativecore/common/config/api/ICreativeConfig

**Comment by CreativeMD** [comment]
Seems like you are missing CreativeCore. Make sure to install CreativeCore and it should work fine. Also make sure to get CreativeCore for the right platform. For Forge get the version for forge (the same goes for fabric obviously).
