### ISSUE TITLE
SUGGESTION: Vision blur transitioning from dark interior to bright exterior

### ISSUE THREAD

**Issue by TheSexyYeti** [CreativeMD/EnhancedVisuals#99]
I've been thinking of this for a while. But kept forgetting to suggest this. But why not have a similar blur that you have from going in and out of water to moving from interior to exterior. Maybe if the player is in an area with a low light level for longer than 5 or 10 minutes. When they go into area with a high light level they get a momentary blur. Like when your eyes try to adjust to the shift in brightness in real life.

**Comment by CreativeMD** [comment]
I feel like this belongs to a shader mod, some shaders already have a feature like this included. I don't know enough to program something like this properly for EnhancedVisuals sorry.
